### PR TITLE
fix(v152): update

### PR DESCRIPTION
**Pull request by vomikan**
make sure your code would work on both windows, linux and osx

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3552)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 7c84ad2bd57bdee07ca0cb30e84037fc54f5199d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: db156664b84a6ee9cacc12d121c15c0a61abc4bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by whalley** [comment]
Signed v1.5.2 MacOS build: https://mmex.ipx.co.uk/mmex-1.5.2-Darwin-2021-06-03.dmg

**Comment by vomikan** [comment]
The release build starts when the tag is installed.

**Comment by whalley** [comment]
Not quite sure what is happening with the v1.5.2 tag. It only has one change from v1.5.1

**Comment by vomikan** [comment]
It seems OK for me 

image

**Comment by vomikan** [comment]
I've retagged the release.

Let's focus on this tag.

image

https://github.com/moneymanagerex/moneymanagerex/releases/tag/untagged-63d97db7cae1fddf0ca0

**Comment by whalley** [comment]
@vomikan  Done. Added build to: https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.5.2

**Pull request merged**
