### PR TITLE
fix(#1089): more that 1 multichoice support

### PR DESCRIPTION
**Pull request by vomikan**
image

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1588)

### CODE REVIEW

**Comment by gabriele-v** [comment]
I think that we should decide how to make it working on Linux and for other entities first, otherwise we could generate conflicts or problem when removing it from transdialog.

**Comment by vomikan** [comment]
I found a way for new GUI looking.
image
Then I'll move custom settings saving from transdialog to separate file.

**Comment by gabriele-v** [comment]
Nice, with the same logic do you think will be possible to move completetely custom fields (not just saving) to a dedicate and common file? Maybe passing the sizer as parameter?

**Comment by gabriele-v** [comment]
To fix problems notices by slodki we need to introduce more code there (Regex validation I.E.), will be nice to have everything not duplicated.

**Comment by vomikan** [comment]
> To fix problems notices by slodki we need to introduce more code there (Regex validation I.E.), will be nice to have everything not duplicated.

I will take care of it.

**Pull request merged**
