### PR TITLE
fix(panels): prevent panels from disappearing on mac

### PR DESCRIPTION
**Pull request by omalleypat**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eb5c64904e49624cfadb5f5eb3e810586248bb88
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: eb5c64904e49624cfadb5f5eb3e810586248bb88
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
We should put an if based on OS. 

With Windows change that you have added doesn't work and instead is correct the previous one. 

There is a trac on wxwidget about it

**Comment by siena123** [comment]
It worked for me on Windows. I tested it before suggesting trying the change.

**Pull request merged**
