### PR TITLE
feat(Stocks.And.Assets): expand functionality  

### PR DESCRIPTION
**Pull request by stef145g**
Allow Stocks and Assets to use the Checking Account transaction table for buying and selling
https://github.com/moneymanagerex/moneymanagerex/issues/336#issuecomment-70448615

This is only added to tests to test out functionality and feasibility at this stage.

### CODE REVIEW

**Comment by guanlisheng** [comment]
Would we have a brief talk about this approach?

**Comment by stef145g** [comment]
Adding external transfers to the **CHECKINGACCOUNT_V1** table is a problem.
The table contains the fields **ACCOUNTID** , **TOACCOUNTID** and a **TRANSCODE**
When **TRANSCODE** == Withdrawal or Deposit, the **TOACCOUNTID** is set to -1
When **TRANSCODE** == Transfer the **TOACCOUNTID** is set to ACCOUNTID of the **to account**.

Transactions using Account --> Transaction  for Withdrawals and deposits is good.
Transactions using Account --> Transaction  --> Account  for Transfers is ok but can be problematic.
Identifying another account type from here is **NOT** ok

Problem occurs in checking account, that we cannot distinguish between an account, an asset or a stock. All transfers are automatically assumed as another account in ACCOUNTLIST_V1

**Solution:**
Provide the new table **TRANSFERTRANS_V1**
This provides a link to the **CHECKINGACCOUNT_V1** table, a link to another table and a table type
Now if we want to link an Asset to an account, for a purchase or a sale, this now becomes easy.
The new table can link the asset to a transaction or not.
- As a transaction, the **CHECKINGACCOUNT_V1** TRANSCODE displays the transaction as a deposit or withdrawal, with the **TOACCOUNTID** pointing to a record in the **TRANSFERTRANS_V1** table.

The new table allows the linking of an Asset or a Stock to one or many transactions that are associated with an account. Any transaction can be easily identified from the Checking Account table. As an added bonus, we can now have an Asset or a Stock in a different currency to the account that the money is being transferred to or from.

In writing this, I have just thought of adding an extra an extra field to the **TRANSFERTRANS_V1**
 table to determine if this is to be accounted as a deposit / withdrawal or not in the checking account.

**Comment by guanlisheng** [comment]
@moneymanagerex/desktop-mmex-team as FYI.
Thinking that we already have stock account, the simple approach might be to add asset account type.

**Comment by stef145g** [comment]
The addition of an Asset Account type would not solve the initial problem which is the way transfers have been originally implemented. This was fine in a simple system, transferring money from account A to Account B. This approach was and is still a problem when it comes to certain report types. Also the introduction of an Asset Account type would introduce other major problems.

Stock accounts represent Stock Portfolios which hold Share accounts. Share accounts are not well managed when it comes to the buying and selling of shares, or receiving dividends from shares. Setting up this structure will correct this issue.

**Comment by vomikan** [comment]
I dont like this idea.
Better to add one more account type ASSET.
In that case 2 feature request will sutisfied.
1 other currency for assets
2 transfers to assets

N


суббота, 24 января 2015 г. пользователь Stefano написал:

**Comment by stef145g** [comment]
If this concept is unacceptable, this pull request can be closed.

**Comment by omalleypat** [comment]
I think being able to transfer from a checking account to a stock account
would be a great feature. For example if I make a contribution to a
retirement account but don't purchase stocks right away, that money is
"lost" to mmex as it is set up now. This has been a request from several
users for many years.

**Comment by stef145g** [comment]
@omalleypat, Thankyou for the positive response.
At this point, I will close this pull request, because I will readjust this table and add the new field.

If I have more positive responses, I will resubmit a modified pull request.

**Pull request closed without merging**
