### PR TITLE
fix(#6113): fix compile errors

### PR DESCRIPTION
**Pull request by n-stein**
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6118)

### CODE REVIEW

**Comment by ovari** [comment]
> No issue with the code, the x64 and Win32 builds both succeeded but AppVeyor storage went offline during the Win32 build so the artifact upload returned a `503: Service Unavailable` error.

@n-stein @vomikan will the updated strings automatically be uploaded to [Crowdin](https://crowdin.com/project/moneymanagerex)? Or is a manual interaction required? Thank you

**Comment by vomikan** [comment]
> Or is a manual interaction required?

In this political situation, I cannot devote more time to the development of the program, but I regularly update the manual pot file. It works through my account.

**Comment by ovari** [comment]
> I regularly update the manual pot file

Thank you

**Comment by vomikan** [comment]
> Thank you

Or maybe you have a desire to set up integration with crowdin ? I would pass on the knowledge that I have. We will get a backup plan.

**Comment by ovari** [comment]
> Or maybe you have a desire to set up integration with crowdin ?

You are too kind. Integration with crowdin is above our skill level. Thank you once again.

**Comment by vomikan** [comment]
> You are too kind. Integration with crowdin is above our skill level. Thank you once again.

I don't understand this answer. It sounds like flattery that precedes a polite refusal. Perhaps this is the cost of the translator. I don't know much about the nuances of English speech.
In other words: Do you want to take on the role of a translation manager?

**Comment by ovari** [comment]
> Do you want to take on the role of a translation manager?

No.

**Pull request merged**
