### PR TITLE
Reports 297

### PR DESCRIPTION
**Pull request by siena123**
make sure your code would work on both windows, linux and osx

### CODE REVIEW

**Comment by guanlisheng** [comment]
@siena123 impressive here. would you please provide some snapshots here to explain what we achieve by this change

@moneymanagerex/desktop-mmex-team

**Comment by siena123** [comment]
The existing report list.
currentreportlist
Has had the date range selections removed.
newreportlist
Additional date range selections are also now available.
selectionlist
All reports which had multiple date ranges available have been updated to show date range selection from panel and to show the date range.
reportpanel
Possible future enhancements.
- Custom date range
- User default date range for reports (or retain last report viewed between sessions)

**Comment by guanlisheng** [comment]
Great work @siena123 !

**Comment by MisterY** [comment]
:+1:

**Pull request merged**
