### PR TITLE
fix(#3101): removed reliance on wxNumberFormatter

### PR DESCRIPTION
**Pull request by whalley**
make sure your code would work on both windows, linux and osx

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3366)

### CODE REVIEW

**Comment by reddyshyam** [comment]
What does this mean?

**Comment by whalley** [comment]
We have been having some issues with 'locale' and the relationship to the mmex currency settings. This change was an attempt to always use the mmex currency settings for number presentation ignoring any system settings.

**Comment by reddyshyam** [comment]
Glad that this is looked into again but the issue with few countries like India, our number system is different.

We represent currency/numbers are 91,23,45,678.90 as against 912,345,678.90 which would have worked out well if locale was picked but sadly that didn't work. I am happy dependency is removed but is there a way we can allow user defined formats, like (2,3) Indian or (3) US?

@vomikan is aware of this but we are waiting for a properly solution available by some library.

**Comment by whalley** [comment]
@reddyshyam Understood. Once we get this bit fixed we can look at making the group sequence more flexible.

**Pull request merged**
