### PR TITLE
Add milestones for v1.7.0 Beta and v1.6.4 to NEWS

### PR DESCRIPTION
**Pull request by joshua-stone**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

Changelog lines derived from the following output:

```
$ gh issue list --repo="moneymanagerex/moneymanagerex" --limit=100 --state="closed" --milestone="v1.7.0" 

Showing 35 of 35 issues in moneymanagerex/moneymanagerex that match your search

#6212  Transaction Report crashes if category starts with `+`                                                               bug, fixed                                about 15 days ago
#6203  Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url" in version 1.7.0 beta.1          bug, duplicate                            about 27 days ago
#6201  Autosort doesn't work on Payee's if search starts with a number                                                      question                                  about 1 month ago
#6185  General Manager Reports                                                                                              enhancement, fixed                        about 17 days ago
#6183  Tags Filtering                                                                                                       bug, fixed                                about 1 month ago
#6154  `Color` not showing in `Transaction Filter` as vertical scrollbar can not go any further down                        bug, linux, fixed                         about 15 days ago
#6143  Rename Full Transactions Report to Account View: All Transactions                                                    i18n, fixed                               about 2 months ago
#6141  MMEX 1.7 Beta 1 - High CPU & GPU usage when Edit Transaction and Transaction Filter dialogs are displayed            bug                                       about 2 months ago
#6140  Dropdown menus issue (duplicated list)                                                                               bug, fixed, mac                           about 2 months ago
#6123  Tags field should not be displayed on New Transaction screen for split transactions                                  question                                  about 1 month ago
#6102  Dashboard Transaction Statistics erroneously includes deleted transactions                                           bug, fixed                                about 3 months ago
#6098  View Since Statement Date does not work unless account statement is Locked                                           bug, fixed                                about 3 months ago
#6096  MMEX icon in ALT+TAB is blurry                                                                                       bug, linux, fixed                         about 3 months ago
#6089  Crash when adding a new asset                                                                                        bug, fixed                                about 3 months ago
#6077  MMEX database Upgrade to version 18 Failed                                                                           bug                                       about 3 months ago
#6071  Saving account - deposit 0, saved as withdrawal                                                                      bug, fixed                                about 3 months ago
#6070  Do not show the space where `Show Money Tips` is shown if option is disabled                                         question                                  about 3 months ago
#6069  Please extend the `Search` field to the end of the window. Thank you                                                 enhancement, fixed                        about 3 months ago
#6065  Presets for CSV import                                                                                               question, imp/exp                         about 3 months ago
#6064  Memory leaks on CSV import                                                                                           bug, fixed                                about 3 months ago
#6063  Strings ordering                                                                                                     i18n, solution found                      about 3 months ago
#6062  Organize vs Organise                                                                                                 i18n, fixed                               about 3 months ago
#6047  mmex 1.6.4 crash after db upgrade to v18 on MacOS                                                                    solution found                            about 2 months ago
#6040  Refresh Stock Prices from Yahoo error "url using bad/illegal format or missing url"                                  bug                                       about 26 days ago
#6036  Crash in theme manager                                                                                               bug, fixed                                about 3 months ago
#5989  Build with wxWidgets 3.2.3                                                                                           enhancement, fixed                        about 3 days ago
#5988  Homepage account balances wrong for some currencies                                                                  bug, fixed, mac, solution found, on hold  about 3 days ago
#5464  Improve budget perfomance report                                                                                     fixed, reports                            about 3 months ago
#5344  macOS menubar Window option position & localization                                                                  bug, fixed, mac, on hold                  about 3 days ago
#5330  MacOS window refresh UI client area corruption                                                                       bug, fixed, mac, on hold                  about 3 days ago
#5329  Distinguish source strings with multiple variables, eg. source: `%1$s blah %2$s` → translation: `%2$s absurdo %1$s`  duplicate, i18n                           about 3 months ago
#5328  bad string (translations issue)                                                                                      i18n, fixed                               about 2 months ago
#1983  Change name of Recurring Transactions to Transaction Planner                                                         enhancement, i18n, fixed, doc             about 2 months ago
#1691  Stock errors                                                                                                         bug, outdated                             about 3 months ago
#1349  Consolidate README.md and README.TXT                                                                                 enhancement, i18n, fixed, doc             about 1 month ago
```

```
$ gh issue list --repo="moneymanagerex/moneymanagerex" --limit=100 --state="closed" --milestone="v1.6.4"

Showing 91 of 91 issues in moneymanagerex/moneymanagerex that match your search

#6032  GUI - minor text improvement in Russian                                                                                                                                  i18n, fixed                           about 4 months ago
#6030  IUSE.L rate                                                                                                                                                              bug, fixed                            about 4 months ago
#6013  Crash when closing QIF import dialog while reports are open                                                                                                              bug                                   about 4 months ago
#5999  Custom decimal field validation bug                                                                                                                                      bug, fixed                            about 4 months ago
#5997  MMEX flatpak is not listed on website                                                                                                                                                                          about 4 months ago
#5975  Transfer arrow points the wrong way on Share Withdrawal transactions                                                                                                     bug, fixed                            about 4 months ago
#5973  Share accounts displayed in Favorites even if "Display Share Accounts" is unchecked                                                                                      bug, fixed                            about 4 months ago
#5969  Incorrect Total Gain/Loss within Stock widget on the Dashboard                                                                                                           bug, fixed                            about 4 months ago
#5966  Crash when deleting or restoring transactions using context menu                                                                                                         bug, fixed                            about 4 months ago
#5964  Constraint error on upgrade from DB 17 to DB 18 when another database is already open                                                                                    bug, fixed                            about 4 months ago
#5962  What does INFOID: 8 relate to please?                                                                                                                                    needs more info, good first issue     about 4 months ago
#5949  bad locale name                                                                                                                                                          bug, solution found                   about 4 months ago
#5948  Error opening encrypted DB                                                                                                                                               bug, fixed                            about 4 months ago
#5947  Error when try to import a .csv file with a subcategory missing                                                                                                          bug, fixed                            about 4 months ago
#5945  DB password change dialog Cancel button                                                                                                                                  enhancement, fixed                    about 4 months ago
#5938  Button not visible in Relocation dialog.                                                                                                                                 bug, fixed                            about 4 months ago
#5926  Erroneous transaction (causes crash on click)                                                                                                                            bug                                   about 4 months ago
#5910  MMEX version 1.6.3 64-bits                                                                                                                                               bug, fixed                            about 4 months ago
#5904  REPORTS - On all charts on V. 1.6.4                                                                                                                                      enhancement, fixed                    about 4 months ago
#5901  Currency Dialog Representation                                                                                                                                           enhancement, fixed                    about 5 months ago
#5894  Can not update stock prices. Get invalid cookie error.                                                                                                                   bug, fixed                            about 4 months ago
#5892  1. Remove `Sub Category:` from budget entry dialog; 2. Show entire category path in `Category:`                                                                          enhancement, fixed                    about 5 months ago
#5890  share update error                                                                                                                                                       bug, fixed                            about 5 months ago
#5885  `Transaction Filter` is bigger than the screen                                                                                                                           bug, fixed                            about 4 months ago
#5875  Initialized when entering Unicode characters in the custom field Tooltip.                                                                                                bug, i18n, fixed                      about 5 months ago
#5870  Check for updates                                                                                                                                                        bug, fixed                            about 5 months ago
#5861  1. Implement `Theme Mode` = `Auto` to select `Light`/`Dark` theme from operating system setting; 2. Rename `Auto` to `System`.                                           enhancement, fixed, theme             about 5 months ago
#5860  Category Report fails reporting 0 even if expenditures are present                                                                                                       bug, solution found                   about 5 months ago
#5857  Crash when using Organize Categories or Organize Payees if transaction report is open                                                                                    bug, fixed                            about 4 months ago
#5855  Stock Portfolios: Click on update throwing Invalid Cookie error                                                                                                          bug                                   about 6 months ago
#5853  Transaction sound                                                                                                                                                        enhancement, fixed                    about 6 months ago
#5852  Crash when creating new database & account                                                                                                                               bug, fixed, win                       about 5 months ago
#5843  Stock Avg Share Price and Total Cost calculation error                                                                                                                   bug, fixed                            about 6 months ago
#5835  Going over Account text field, using Tab, deletes selected account                                                                                                       bug, fixed                            about 6 months ago
#5834  Incorrect total net worth reported on Dashboard                                                                                                                          bug, fixed                            about 6 months ago
#5833  Summary of stocks Gains/Loss currency exchange error                                                                                                                     bug, fixed                            about 6 months ago
#5832  Transaction Details panel becomes unnecessarily wide when custom field contains data                                                                                     bug, fixed                            about 6 months ago
#5830  Auto recurring transaction crash                                                                                                                                         bug, fixed                            about 6 months ago
#5828  Stock and Asset transactions can be copied/pasted using keyboard                                                                                                         bug, fixed                            about 6 months ago
#5823  View Trans window for Stock transaction - make it larger/resizable please.                                                                                               bug, fixed                            about 6 months ago
#5817  Transaction Filter does not work correctly when changing an account                                                                                                      bug, fixed                            about 6 months ago
#5813  Range options in transaction filter have no effect                                                                                                                       bug, fixed                            about 6 months ago
#5812  Transaction report: option to group by ID                                                                                                                                enhancement, fixed                    about 6 months ago
#5809  Account, Payee and Category dropdown lists are not active                                                                                                                bug, fixed                            about 6 months ago
#5808  New Tranaction widnow is growing after reopening and can't be shrinked down                                                                                              bug, linux, fixed                     about 6 months ago
#5792  Extra date format required.                                                                                                                                              enhancement, fixed                    about 6 months ago
#5791  Colour settings are not saved with the template on import dialogs                                                                                                        bug, fixed                            about 6 months ago
#5790  Associate an import/export Preset (template) name with an account                                                                                                        enhancement, fixed                    about 4 months ago
#5774  Locale is carried over between databases.                                                                                                                                bug, fixed                            about 6 months ago
#5772  CSV Import - "Type" defined amount sign does not work                                                                                                                    bug, imp/exp, fixed                   about 6 months ago
#5769  RESOCONTO OPERAZIONI - FILTRO NON VA QUANDO SALVATO                                                                                                                      bug, fixed                            about 6 months ago
#5759  Automatically Download Stock Prices at Startup                                                                                                                           enhancement, fixed                    about 4 months ago
#5752  Transaction Report Filter does not work with Split Transaction Notes                                                                                                     bug                                   about 7 months ago
#5709  Titlebar display order: 1. database filename; 2. localized program name. `Recent Files` menu: 3. Add database directory                                                  enhancement                           about 7 months ago
#5706  Split Transaction Notes are not exported to QIF files                                                                                                                    enhancement, fixed                    about 6 months ago
#5686  Budget view crash on double click category summary                                                                                                                       fixed                                 about 8 months ago
#5683  Cancel add asset transaction when creating new asset crashes MMEX                                                                                                        bug, fixed                            about 6 months ago
#5670  MMEX crashes on asset transaction when "Last Used" is set for Default Payee, "Last used for payee" is set for Default Category, and the last transaction was a transfer  bug                                   about 8 months ago
#5668  Make Dialogs resizable                                                                                                                                                   enhancement                           about 6 months ago
#5659  Changes `Files` to `File` in `Import from`                                                                                                                               enhancement, fixed                    about 8 months ago
#5658  Changes keyboard shortcuts in `Accounts` menu                                                                                                                            enhancement, fixed                    about 8 months ago
#5656  Show count of selected/filtered/total records in the view                                                                                                                question                              about 8 months ago
#5655  Change `Url` to `URL`                                                                                                                                                    enhancement, fixed                    about 8 months ago
#5650  Add ellipsis to "View with Transaction Filter" menu option                                                                                                               enhancement, fixed                    about 8 months ago
#5643  Can´t add Initial Balance on Polish Zloty (PLN) Currency                                                                                                                 bug                                   about 6 months ago
#5641  Imported transactions from webapp not working correctly                                                                                                                  bug, needs more info                  about 8 months ago
#5636  Change `system default` to `System default` and other minor improvements                                                                                                 enhancement, fixed                    about 8 months ago
#5630  Transaction not deleted                                                                                                                                                  bug, fixed                            about 6 months ago
#5629  1. Please expand `Search` field; 2./3. remove spaces ` ` before and after `/`; 4. `Show All` keyboard accelerator                                                        bug, linux, fixed                     about 8 months ago
#5628  Please allow title `Currency Manager` to be translatable                                                                                                                 bug, i18n, fixed                      about 8 months ago
#5626  Please allow `locale::facet::_S_create_C_locale name not valid` to be translatable                                                                                       bug, fixed                            about 8 months ago
#5625  Please allow `Normal`, `Enlarged`, `Large`, `Huge` to be translatable                                                                                                    bug, i18n, fixed                      about 8 months ago
#5618  Crash on selecting share price in investment window (see Image)                                                                                                          bug, stocks-shares                    about 7 months ago
#5615  1.6.3 keyboard shortcuts do not work anymore                                                                                                                             bug, fixed                            about 8 months ago
#5614  Recurring transactions.                                                                                                                                                  bug                                   about 8 months ago
#5606  Search Feature issue introduced 1 - 2 updates ago not resolved                                                                                                           bug, fixed                            about 1 month ago
#5602  QIF import date format                                                                                                                                                   bug, imp/exp, fixed                   about 8 months ago
#5599  Transaction Report / Categorie                                                                                                                                           bug                                   about 6 months ago
#5590  GRM text box context menu is not translated                                                                                                                              bug, i18n, fixed                      about 8 months ago
#5576  Issue importing attachment to the desktop application                                                                                                                    bug, solution found                   about 8 months ago
#5573  Budget Performance Report                                                                                                                                                bug, fixed, reports                   about 8 months ago
#5571  Deleted Transaction Dialog Titlebar                                                                                                                                      enhancement                           about 8 months ago
#5568  MMEX database upgrade to version 17 failed                                                                                                                               bug, fixed                            about 6 months ago
#5465  Show only subtransactions that match the filter                                                                                                                          enhancement                           about 7 months ago
#5451  Missing currency ZMW Zambian Kwacha                                                                                                                                      bug, fixed                            about 6 months ago
#5394  for "all transactions" CRTL+c does not work                                                                                                                              bug                                   about 6 months ago
#3684  Drag and Drop to import file in correct account                                                                                                                          feature, fixed                        about 4 months ago
#3148  Payee matching                                                                                                                                                           feature, fixed                        about 6 months ago
#2361  Conversion rate input for transfer type 'Transaction' Advanced (checked)                                                                                                 enhancement, feature, solution found  about 6 months ago
#1806  MMEX Flatpak listing on Flathub                                                                                                                                          enhancement, linux, fixed             about 4 months ago
#1254  Register filetypes for mmex at system level in Linux                                                                                                                     enhancement, linux                    about 4 months ago
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6257)

### CODE REVIEW

**Comment by vomikan** [comment]
https://github.com/moneymanagerex/moneymanagerex/issues/4058

**Comment by joshua-stone** [comment]
> #4058

What's the context of this?

**Comment by joshua-stone** [comment]
@vomikan BTW, if you're having issues downloading release data, then you may have to ensure that you have pagination logic in place and/or use an API token to avoid getting rate-limited. Here's what I use for introspecting release information:

https://github.com/joshua-stone/github-stats/blob/4c26a0d47c3fec32c11e866e3ccf2c5cb9dbc7ba/github-download-stats.py#L52

**Comment by ovari** [comment]
Will 1.7.0 beta now show on [Flathub](https://flathub.org/apps/org.moneymanagerex.MMEX)?

Will Flathub installs update to 1.7.0 beta?

Thank you

**Comment by joshua-stone** [comment]
1.7.0 Beta will not show up on Flathub since a new release hasn't been tagged. There's a stable branch for MMEX set up on flathub, and it's currently pointed to [1.6.4](https://github.com/flathub/org.moneymanagerex.MMEX/blob/279d4de847a9f08314fffec699b3d84fc1ec0a38/org.moneymanagerex.MMEX.yml#L53):

https://github.com/moneymanagerex/moneymanagerex/commit/63f03cb3d968b8933ca3378c12a6576e26706803

I'm not sure it would make sense to set up a development branch on Flathub as well when MMEX's CI already produces .flatpak artifacts to test with:

https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex?branch=master

I think it would be reasonable to have MMEX's CI be used for testing flatpak builds and have Flathub's CI produce stable builds.

**Pull request merged**
