### PR TITLE
Naming convention and artifacts deployment

### PR DESCRIPTION
**Pull request by tomasfrtala**
## What is new

- Lightening the Travis builds of the clang to cover only gcc that is standard installed on linux distribution.
Now for linux distributions Travis builds an artifacts using dockers (from a docker file located in our project dir `dockers`). More distributions can be found here https://hub.docker.com
- Added support for naming convention of `ALPHA`, `BETA`, `RC` artifacts also with numbering.
- Deployment artifacts to github release
- Deployment rpm, deb packages to packagecloud repository

### Github releases for distributing artifacts
Done alternative distribution of artifacts. For making deploying work with github release you need to acquire your personal **token** from this page https://github.com/settings/tokens by clicking `Generate new token` and copy it for example to notepad/vim because this token you will need later.

### PackageCloud repository for distributing linux deb, rpm packages
Same as in github case. Acquire token under drop down menu select `API Token` and then copy the value of **API token**.

#### Travis
Under drop down menu select `More options -> Settings`
And in the `Environment Variables`
add name `api_key` and paste copied **token** and ensure that the `Display value in build log` is set to `OFF`. This will be for releasing to github.
Again add new entry and name it `PACKAGECLOUD_TOKEN` and paste copied **API token** and ensure that the `Display value in build log` is set to `OFF`. This will be for releasing to packagecloud.

#### Appveyor
Under your logged user from drop down option select `Encrypt data` paste the copied **token** inside `Value to encrypt`, click `Encrypt` and copy `Encrypted value` and paste it to `appveyor.yml` and `appveyor.yml.in`

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1140)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 395cbda3471ad26e864a809f96ae989384ce83e6
  * Your subject line is longer than 100 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by tomasfrtala** [comment]
I forgot to mention that deployment is performed only on tags. You can see this in configs:
```
travis config
on:      
    # Deploy only when tag is specified
    tags: true

appveyor config
on:                                                   
    #branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
```

**Comment by tomasfrtala** [comment]
@stef145g There two ways of solving this problem:
- by uncommenting [Publishing artifacts](https://github.com/moneymanagerex/moneymanagerex/pull/1140/files#diff-180360612c6b8c4ed830919bbb4dd459R67) and commenting [line 73](https://github.com/moneymanagerex/moneymanagerex/pull/1140/files#diff-180360612c6b8c4ed830919bbb4dd459R73) till end. Artifacts will have build number in appveyor and when releasing to github switch back commenting.
- or by adding build number as part of the [rename process](https://github.com/moneymanagerex/moneymanagerex/pull/1140/files#diff-180360612c6b8c4ed830919bbb4dd459R62) and also deployed artifacts to github release will have build number.

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 395cbda3471ad26e864a809f96ae989384ce83e6
  * Your subject line is longer than 100 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 395cbda3471ad26e864a809f96ae989384ce83e6
  * Your subject line is longer than 100 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by tomasfrtala** [comment]
All systems are green. Deployment to [github releases](https://github.com/tomasfrtala/moneymanagerex/releases) and to [package cloud repository](https://packagecloud.io/moneymanagerex/moneymanagerex) is working.

**Pull request merged**
