### PR TITLE
feat(Import.qif.account): QIF import 

### PR DESCRIPTION
**Pull request by loki36**
ability to chose account number instead of account name to match account #387

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f314ff2056a38d8bb449ae61eddfdb7278ec398c
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f314ff2056a38d8bb449ae61eddfdb7278ec398c
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by loki36** [comment]
we could create a unique index on table based on accountnum or based on  heldat(accountbank) + accountnum ?

**Comment by guanlisheng** [comment]
Technically, we could.
I don't think it's correct base on existing usage about account number.
So do we plan to use it to identify an account, treat it same as account name and id?

**Comment by loki36** [comment]
an other approach would be to have the "accoutname" and the "accountdysplayname" and set accountdysplayname equal to accountname if it not set . But we need after that to change everywhere in gui the accountname by accountdysplayname.

**Comment by vomikan** [comment]
I hope will have time to discover this tonight.

**Comment by loki36** [comment]
not really sure to understand.

**Comment by vomikan** [comment]
@loki36 Could you provide QIF file with account number?
There is only "Number of the check" in the QIF specification.

**Comment by loki36** [comment]
yes, it's because the account number is in the field NAccount Name

an qif example file : http://owncloud.far.bongrand.fr/public.php?service=files&t=291345253e6918a6658cd882d9049407
link will expire by the end of march

**Comment by vomikan** [comment]
I see. Other words, in mmex U prefer to have aliace for account names. At the same time a bank provide account number for QIF file.
In that case U have provided nice feature.

**Pull request merged**
