### PR TITLE
refactor(travis): build only one Mac package

### PR DESCRIPTION
**Pull request by slodki**
A binary compiled with --with-macosx-version-min should work on all never macOS versions too:
- [ ] 10.7 Lion
- [ ] 10.8 Mountain Lion
- [ ] 10.9 Mavericks
- [ ] 10.10 Yosemite
- [x] 10.11 El Capitan
- [ ] 10.12 Sierra
- [x] 10.13 High Sierra
- [ ] 10.14 Mojave

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1824)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 07ccf9b3b7d69f8f11a00274cdf3d7e77e6eafca
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 07ccf9b3b7d69f8f11a00274cdf3d7e77e6eafca
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 0ca75d1b34b136e62b5432d529cc5930f8ae699b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: bcec8ccfca087c3cbb3f641798dfb345486f1892
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
@bingalls @bestlem @michalkoza @omalleypat @wirmike @xraynaud @ahmadsyamim @MediaAlex @palibby @andersonvom @sndgibson @jax79sg @mconsonni @EvBef @vinodraut @alex-gee
Could you verify [this Mac package](https://github.com/slodki/moneymanagerex/releases/download/macos-test/mmex-1.4.0-alpha.6-macos.dmg) can be run on different macOS versions (10.7...10.14) and post here the results?

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: bcec8ccfca087c3cbb3f641798dfb345486f1892
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
@xraynaud Can you retry with updated package from link above?

**Comment by xraynaud** [comment]
New version works on 10.13.

**Comment by bingalls** [comment]
Nice work! Latest 1.4.0 alpha6 works on 10.11.6 El Capitain, the most recent OS for old 64bit Macs.
Note the following annoyances:
* Code is unsigned (I expect this won't be fixed, but this is a financial app)
* Translations won't load, and I can't find an user preference for this. Fortunately, the default is now English
* Opening a database upgrades it with a notice, but no _prompt_ for user permission. 
* Worse, It is not clear to users if a db copy is made, nor a way to export to an older version. Perhaps  a good QIF export could work

**Comment by slodki** [comment]
@bingalls Available translations should be listed under `View` &rarr; `Switch Application Language` menu in MMEX. Please report if it's not working.

DB is upgraded without user confirmation because backup is auto-created before upgrade. But this can be easily changed.

There is no downgrade procedure for MMEX db as new features require new data structures. Downgrade will lose some user data.

**Comment by bingalls** [comment]
@slodki OK, I was looking in Settings to change language; the View menu _fixed the problem_. I had been on the default language. Offering this advice in the popup will make a better UX, than a technical error message.
The `file` command tells me that this desktop release is at sqlite 3 user version 13
Both the stable & beta Android release are at user version 7. This means that I could not test sharing files.

**Comment by slodki** [comment]
https://github.com/moneymanagerex/moneymanagerex/wiki/Upgrade-to-1.4.0-problems
moneymanagerex/android-money-manager-ex#1245

**Pull request merged**
