### PR TITLE
feat(db.upgrade): add new upgrade procedure and add new fields

### PR DESCRIPTION
**Pull request by gabriele-v**
Solves #709 #488

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
It will be automatically removed on connection closed, but you are right, I'll fix to drop it to prevent high memory usage..

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by guanlisheng** [comment]
@gabriele-v the CI is failed....

**Comment by gabriele-v** [comment]
I don't know why you have always to immediately close requests, lets dev some time to fix them! 

It's obvious that it fails, because makefile need to be updated, but I don't know how to do it..

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by guanlisheng** [comment]
any guy want to review this pr? @moneymanagerex/desktop-mmex-team

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
I've added version in backup filename before upgrade

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
I've added two changes:
- Revert to v4 (we will upgrade to v5 only in MMEX 2.0.0)
- Add support for MMDBG files that can help a user with upgrade problems/errors

If upgrade fails, a user can load a file (provided by MMEX Support team) that has **.MMDBG** extension, practically it's a pure text file. MMEX will search in first line of file:
- if equals to "**-- MMEX Debug SQL - Read --**" will execute all SELECT statements of below lines and provide result to user (screen or file depending on what he chooses), so it can upload it to us without need of full DB upload (lots of users cannot do it for privacy reason)
- if equals to "**-- MMEX Debug SQL - Update--**" will execute all UPDATE\DROP\INSERT statements of below lines so we can fix user DB without any external program

I know it could be dangerous, but it will help us a lot helping users with DB upgrade errors.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by stef145g** [comment]
Tests done on initial PR -- Working OK
Retested @gabriele-v:master after reset, now fails to upgrade or open an old database.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
@stef145g you are right, seems that SQLite doesn't accept a statement made by a comment only without any query.
I havent' found a wxSqlite function that check if a query it's valid (tried _wxSQLite3Database::CheckSyntax_ and _wxSQLite3Statement::IsOk_ but both failed), anyway should be fixed now with another workaround.

**Comment by stef145g** [comment]
@gabriele-v, This works.
I have also created a PR to your master branch. I don't know if you receive notifications of this.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
I don't receive any notification..
Merged, thanks.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e41f56e3e205e476e6292ad9c14c338edf84235
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
@stef145g Could you merge if you think it's ok and enough stable?
Changes are quite big and I need to manually solve conflicts every time that I merge master..

**Comment by stef145g** [comment]
@gabriele-v Please send pull request for database repo so @guanlisheng can merge it.

**Pull request merged**
