### PR TITLE
Json store 

### PR DESCRIPTION
**Pull request by stef145g**
Using json to store extra account information using the existing table infotable_v1
Features implemented in the following issues: #451, #538, #567

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/859)

### CODE REVIEW

**Comment by gabriele-v** [comment]
Stefan, I completely disagree on this implementation.

Surely JSON it's the simplest way, but now that we have upgrade DB process working, why we need to complicate DB structure inserting JSON data and in another table that should contain only information? Good luck if you try to extract them with a SQL query for GRM..

Simply alter table account_v1 adding needed fields.

@moneymanagerex/desktop-mmex-team what do you think?

**Comment by MisterY** [comment]
@gabriele-v, this was my first thought as well. I just came here to see if it is possible at all to use this in the Android version. Without any spec on schema, now it is even more fluid in how we implement features or at least keep them in sync among different platforms.
It is unfortunate that we are not making more efforts in pushing the schema upgrade mechanism to production. There are many useful features waiting on this.
I thought extending the credit card account information would be one of those that would really benefit and bring some UI goodness in the mobile app as people track their spending. However, by mixing JSON structures with SQL tables, it just gets messier. Besides, I do not understand the reasoning behind. Are there any issues with extending the database schema?

On the positive side, @stef145g, I'm really happy that you moved in the direction of implementing these features. Wish it was done a bit earlier so that I could implement them for Android in parallel before the Summer holidays but it will do for an Autumn update. I'm really looking forward to adding progress bars on credit cards. This is one of the most useful options for credit accounts.

**Comment by stef145g** [comment]
For me, creating a JSON store was a way of understanding JSON. It proved very useful to me as it was a quick way of prototyping long awaited features. Now that these features are in place, it now becomes a simple procedure to transfer the storage to the database file. Another reason for creating methods in a JsonAccount class. The JsonStore class should be able to simplify other existing data storage cases. 

While I agree with Gabriele about GRM, the current implemented fields are mainly used for control purposes, and possibly would not be used in a report.

I will withdraw this pull request after a few days to allow others to comment on the GUI implementation. These features can be excluded from v1.3 and added in a future release, when we have updated the database.

**Comment by stef145g** [comment]
Removed the Account storage using JSON data. New fields have now been added to the account table.
Converting this to database storage was easier that I thought.

**Comment by MisterY** [comment]
Who can merge the database changes? https://github.com/moneymanagerex/database/pull/16
I'd love to update the schema in the Android app and perhaps start development utilizing the new fields.

**Pull request merged**
