### PR TITLE
fix(#1089) refactoring

### PR DESCRIPTION
**Pull request by vomikan**
image

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1580)

### CODE REVIEW

**Comment by slodki** [comment]
Could you show GUI project for custom fields manger/editor?
Will it be possible to display custom field as column in transaction panel and search for user entered value?

**Comment by vomikan** [comment]
@slodki 
1. 
image

2. In future some custom fields should be presented in checking panel. Also a custom data should be searchable.

**Comment by vomikan** [comment]
Merged but still one bug is present. 
I can't fix issue: If transaction is new custom settings will fals to save.

**Comment by gabriele-v** [comment]
@vomikan 
1. Why merge changes that break some functionality (save on new transaction)? Also, I think that changes should be reviewed by someone else, not auto-merged by yourself.

2. Personally I disagree about changes of this pull request, because you have moved all custom fields logic into transaction dialog, increasing the complexity of transdialog (that it's already huge) and specially now you have isolated customfields to transaction only. With previous implementation, custom fields will be ready to be used everywhere in MMEX (like attachments), now they are usable just in transactions.

For that reasons I suggest to revert back this pull request (we just need to make previous implementation working on Linux/Mac), @moneymanagerex/desktop-mmex-team what do you think?

Sorry but for work reasons I cannot be more present/developing, but I still follow MMEX main changes.

**Pull request merged**
