### PR TITLE
fix(translation.po): update 'spanish.po' completed

### PR DESCRIPTION
**Pull request by kolmo7**
It needs to be reviewed again to see if they are all translated strings and once the language file is available for use with version 1.2.0 alpha

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ccf3a613f9bcac64c2706adc43a79a3230f6005d
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ccf3a613f9bcac64c2706adc43a79a3230f6005d
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by guanlisheng** [comment]
Hi @kolmo7 , would you mind to check why the build failed?

**Comment by vomikan** [comment]
I've pushed it directly. Will see...

**Comment by vomikan** [comment]
https://travis-ci.org/moneymanagerex/moneymanagerex/builds/46841236
Passed

**Pull request closed without merging**
