### PR TITLE
fix(#1301): icons update

### PR DESCRIPTION
**Pull request by vomikan**
screenshot 562

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1335)

### CODE REVIEW

**Comment by slodki** [comment]
And the bug should be lighter a little IMHO. But it's much better then previous one! :-)

**Comment by vomikan** [comment]
language16
language24
language32
language48

**Comment by vomikan** [comment]
screenshot 566
screenshot 565

**Comment by vomikan** [comment]
https://www.shareicon.net/tag/language

**Pull request merged**
