### PR TITLE
Some cleanups

### PR DESCRIPTION
**Pull request by gerstrong**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5940)

### CODE REVIEW

**Comment by n-stein** [comment]
@gerstrong 

The Bit-library file lbitlib.c was removed from lua by commit de2caf7ee4dfc7d641d00bf1d74b261482993b2d. You need to remove this line from 3rd/CMakeLists.txt to fix the AppVeyor build:

https://github.com/moneymanagerex/moneymanagerex/blob/e59e03d20b76ca3b22a64d75465106d3d178a7f2/3rd/CMakeLists.txt#L44

**Comment by vomikan** [comment]
util.cpp:1309:95: error: useless cast to type 'class wxString' [-Werror=useless-cast]

**Comment by n-stein** [comment]
Not sure we can update all submodules. Charts no longer work on this build:

image
image

**Comment by vomikan** [comment]
I suggest making such changes in small steps. On the eve of the release, unnecessary bugs should not be allowed.

**Pull request closed without merging**
