### PR TITLE
Revised Cmake to produce deb and rpm packages

### PR DESCRIPTION
**Pull request by tomasfrtala**
Based on the issue #974 and #1013 I decided to help with generating packages. It is made with the help of cmake.
Resulted built packages was evaluated in Fedora 25 and Ubuntu 16.04. I also added installation guide for creating .rpm based packages.
NOTE: Produced version is 1.3.0 that is behind actual 1.3.3

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1084)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 6262256acfb7db161134418f5de889abc3524ff7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d7aefc7ce6738281ce6811a14d1e314643a35844
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by tomasfrtala** [comment]
In the future I will adapt my commit messages to be more harmonized with you.

**Comment by stef145g** [comment]
This pull request cannot be directed to the master branch. This is because it is generated off the cmake branch. See attached Revision Graph
untitled

**Comment by stef145g** [comment]
I have rebased the cmake branch against v1.3.x and created a new resulting branch cmake_v1.3.x
Please check this to see if it works on v1.3.3

**Pull request closed without merging**
