### PR TITLE
fmt is available in fedora repositories

### PR DESCRIPTION
**Pull request by bkmgit**
This need not be downloaded separately

Not sure this needs an update of release notes. Can do so though.

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5184)

### CODE REVIEW

**Comment by bkmgit** [comment]
Partially addresses https://github.com/moneymanagerex/moneymanagerex/issues/5185

**Comment by whalley** [comment]
@bkmgit  We include fmt as part of the MMEX builld.
https://github.com/moneymanagerex/moneymanagerex/tree/master/3rd currently we use https://github.com/fmtlib/fmt/releases/tag/8.1.1

Why do we need fmt-devel ?

**Comment by bkmgit** [comment]
The devel package has headers useful for building.

**Comment by whalley** [comment]
> The devel package has headers useful for building.

But we pull the full source for fmt to build MMEX anyway? What else do we need? I'm confused.

**Pull request merged**
