### PR TITLE
feat(#622): multiline select copy to clipboard

### PR DESCRIPTION
**Pull request by siena123**

### CODE REVIEW

**Comment by siena123** [comment]
The account panel showed since of being a multi-select control at one time.

**Comment by vomikan** [comment]
1. Copy/Past single transaction has lost;
2. Amounts transformed into dates

**Comment by siena123** [comment]
1. Copy/Paste single transaction is working for me. If multi select copy is done the prior single select copy in mmex gets cleared so paste is not available until another single select copy is done. 
2. Amounts are not transforming into dates for me. I have pasted data into both a text editor (notepad) and into the OpenOffice spreadsheet application. Both Excel and OpenOffice have options to specify the format of the column when data gets pasted into the program (may require multi-line paste). You may need to specifically specify the format for the column if you still have the problem as it is an issue with the spreadsheet application incorrectly auto-detecting the column format. 

One other item to note is that the format is tab delimited for the copy/paste so as to not need to deal with a text delimiter if using comma delimited format or one of the other commonly used delimiters which could be in the notes field. 

- James

**Comment by vomikan** [comment]
Sorry I've updated the posting after first comit.


   1. The amounts transformed into dates in Excel.
   2. After Copy/Past single transaction into the account the selection
   contains both: original and new transaction.
   3. If, for example, 3 transaction selected then right click on them - as
   result only 2 transaction selected.
   4. After delete single transaction - two transactions selected


2016-01-25 16:25 GMT+03:00 siena123 <notifications@github.com>:

**Comment by siena123** [comment]
1. When you paste the data into Excel it should open the import data wizard and on the 3rd page you have the option to specify the column format for the imported data from general to number which should fix the problem with Excel auto detect format for general transforming the data. Also on the 3rd page you have an advanced button that you can specify the decimal and thousands seperators.

2-4. I have been able to reproduce the problem and will work on a fix.

**Comment by siena123** [comment]
Fixes pushed up for the 3 issues I could reproduce.
The other issue I don't see as being a problem in mmex but a user issue with Excel.

**Pull request merged**
