### PR TITLE
mongoose update to v 6.5

### PR DESCRIPTION
**Pull request by vomikan**
make sure your code would work on both windows, linux and osx

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/889)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 5ce6f16e2d870b0eecc82a491f607e039d0d652e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 5ce6f16e2d870b0eecc82a491f607e039d0d652e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by guanlisheng** [comment]
Why we changed other files?

**Comment by vomikan** [comment]
To updated I firstly delete the submodule. I that case the .submoduled file has changed.

**Comment by guanlisheng** [comment]
Why we changed src/webserver.cpp ?

**Comment by vomikan** [comment]
becouse warning C4189

**Pull request closed without merging**
