### PR TITLE
feat(Repeating.Transactions): replace next occurance with payment and due dates

### PR DESCRIPTION
**Pull request by stef145g**
On existing databases, all Repeating Transactions need to be edited to reset the due date.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e8352b21c621e43099654e345577cbdf16a306a0
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e8352b21c621e43099654e345577cbdf16a306a0
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by guanlisheng** [comment]
seems we need a manual data migration for end user ?

**Comment by stef145g** [comment]
Yes to some degree.
The home page will display all pending transactions as being overdue.

**Requirement:** All repeating transactions should be opened in edit mode, and saved. If nothing is changed, the due date will be automatically set to the payment date. This is because the Due date cannot be set to a date before the payment date. This will correct the home page display.

The data change is backward compatible.

**Comment by gabriele-v** [comment]
We should make a DB patch at start-up to fix it. 
We will have lots of users that notice this like a bug (and they are right..)

**Comment by stef145g** [comment]
Agreed.
I have created a patch to fix this, but will also upgrade the database version.
https://github.com/moneymanagerex/moneymanagerex/pull/347

The database version is tested and any database at version 2, will have the fix applied, and updated to version 3. Subsequent actions will not affect the database.

**Pull request merged**
