### PR TITLE
fix(#879): fix crash and improvements

### PR DESCRIPTION
**Pull request by vomikan**
- provided transaction type for the categories manager (for future development)
- fix crash for hiden categorias

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/881)

### CODE REVIEW

**Comment by guanlisheng** [comment]
this is incorrect and please refer the comment in #879

**Comment by vomikan** [comment]
@guanlisheng what does 'invalid' label mean in this content?

**Comment by vomikan** [comment]
Seems you didn't read the code.

**Comment by guanlisheng** [comment]
i just merged the PR.  for the variable renaming, i recommend to use a separate PR to distinguish the logic change or just formatting.

**Comment by vomikan** [comment]
How to revert this changes back?
I am working on new PR for https://github.com/moneymanagerex/moneymanagerex/issues/888

**Pull request merged**
