### PR TITLE
Rapidjson

### PR DESCRIPTION
**Pull request by stef145g**
Rapidjson branch rebased onto master. Needs to be tested as conversion not completed

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1496)

### CODE REVIEW

**Comment by vomikan** [comment]
```

/moneymanagerex/src/webserver.cpp: In function 'void handle_sql(mg_connection*, http_message*)':

/moneymanagerex/src/webserver.cpp:68:76: error: cannot pass objects of non-trivially-copyable type 'class wxCStrData' through '...'

                 "Content-Length: %zu\r\n\r\n%ls", str.length(), str.c_str());
```

**Comment by vomikan** [comment]
```std::wstring str = ss.str();
    std::cout<<str<<std::endl;
    mg_printf(nc, "HTTP/1.1 200 OK\r\n"
                "Content-Type: application/json; charset=utf-8\r\n"
                "Content-Length: %zu\r\n\r\n%ls", str.length(), str.c_str());``` 


| 1 | 2 |
|---|---|
|  |  |

**Comment by vomikan** [comment]
I suggest the following:
```
    const char* str = json_buffer.GetString();
    std::cout<<str<<std::endl;

    mg_printf(nc, "HTTP/1.1 200 OK\r\n"
                "Content-Type: application/json; charset=utf-8\r\n"
                "Content-Length: %zu\r\n\r\n%ls"
        , sizeof(str) / sizeof(char), str);
```

**Comment by stef145g** [comment]
I have committed a fix with your suggestion.

**Comment by vomikan** [comment]
@stef145g I am not sure if ```%ls``` is correct.
modificatol ```l``` don't used with s.

**Comment by stef145g** [comment]
Resubmitted the commit

**Pull request merged**
