### PR TITLE
V1.2.x mac build fixes

### PR DESCRIPTION
**Pull request by omalleypat**
Needed to get the help file to show properly for GRM.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 154f48e6165f222dbe0d89841361b76a82a56746
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format**

 * Commit: 4d1d571f91274d30c75e46362d683a8e09a82c7f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 8b00ef09add4b3fcbcfe49bd7b71b2ab62a985bc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 73007ef1e25f4a54cb8e620fd36e221254515d2f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7b413d1fad4040f45056277d53f14ade10071543
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1547702541a4e0f0e615058409dd1820cc1d6f8c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 154f48e6165f222dbe0d89841361b76a82a56746
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format**

 * Commit: 4d1d571f91274d30c75e46362d683a8e09a82c7f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 8b00ef09add4b3fcbcfe49bd7b71b2ab62a985bc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 73007ef1e25f4a54cb8e620fd36e221254515d2f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 7b413d1fad4040f45056277d53f14ade10071543
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 1547702541a4e0f0e615058409dd1820cc1d6f8c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by omalleypat** [comment]
I really only wanted 1547702 in this PR, something is messed up. If anyone can help, I'd appreciate it. I'm stuck on how to get out of this mess.

**Comment by omalleypat** [comment]
Also I don't have a functional bakefile at the moment, so I guessed at those commands. The changes in Makefile.in are the ones I made and tested for commit 1547702

**Comment by stef145g** [comment]
All is OK.
The other commits presented were the catch-up commits as a result of merges from other non synched branches, which were included.

**Pull request merged**
