### PR TITLE
fix(cmake): allow to load MMEX project to VS2017 directly and run

### PR DESCRIPTION
**Pull request by slodki**
Updated BUILD.md documentation.

Changes in CMake scripts:
* Include more CMake patches to add support for latest MSVC 1911
* Move Visual Studio IDE tuning commands to right place
* Fix executable file output path under MSVS
* Add more build tools versions to versions.h and about dialog
* Always include UCRT DLLs as they are required i many Windows versions
* Distribute correct DLLs (official downloaded or compiled locally) if
  linking to shared wxWidgets
* Fix generating translations with Ninja
- fix VS startup project - now points to mmex target
- minor style fixes
- removed not used CMakeSettings.json file

Changes in Travis & Docker:
- Add latest Debian (buster) package
- Add automake and libtool to docker images to allow cppunit compile

Changes AppVeyor:
* Fix build problems with VS2017 and latest AppVeyor image version
* Improve wxWidgets binaries caching (not cross cache size limit)
* Add ability to link to shared wxWin libraries (DLLs)
* Try download official pre-compiled wxWin binaries before local compile
* Build only selected matrix combinations
- optimize developer command prompt initialization for different VS versions
- remove v90 and v100 as unavailable at AppVeyor
- add v110 support - but now fails with compile errors
- fix YAML style

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1308)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 2be46fb4e2aeaf012b7b808b13be5d18e7ec0ca7
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
Updated [BUILD.md](https://github.com/slodki/moneymanagerex/blob/update-cmake2/BUILD.md) instructions for Windows with 3 different scenarios tested on Windows 8.1 with VS2017.

CLI builds [tested with VS2013 and VS2015](https://ci.appveyor.com/project/slodki/moneymanagerex/build/817) using AppVeyor images. 48 different binary packages ready to download.

Please test IDE builds with VS <=VS2015.

**Comment by slodki** [comment]
This PR is continuation of #1302 and related to #1307, #1306, #1299, #1296, #1293, #1272, #1214, #1126.

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: db23e174f68d187120eec11ae7971dff3acfca65
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
CMake patches waiting for upstream merge: [1192](https://gitlab.kitware.com/cmake/cmake/merge_requests/1192), [1193](https://gitlab.kitware.com/cmake/cmake/merge_requests/1193), [1194](https://gitlab.kitware.com/cmake/cmake/merge_requests/1194). One ([1168](https://gitlab.kitware.com/cmake/cmake/merge_requests/1168)) will be in next CMake version 3.9.2.

**Comment by slodki** [comment]
Please comment if selected Windows build matrix elements to run and distribute to end-users is optimal:

* comp=141; Platform: x64
* comp=141; Platform: Win32
* **comp=141, wxShared=1; Platform: x64**
* **comp=141, wxShared=1; Platform: Win32**
* comp=141, xp=_xp; Platform: x64
* comp=141, xp=_xp; Platform: Win32
* comp=141, xp=_xp, wxShared=1; Platform: x64
* comp=141, xp=_xp, wxShared=1; Platform: Win32
* comp=140; Platform: x64
* comp=140; Platform: Win32
* comp=140, wxShared=1; Platform: x64
* comp=140, wxShared=1; Platform: Win32
* comp=140, xp=_xp; Platform: x64
* comp=140, xp=_xp; Platform: Win32
* comp=140, xp=_xp, wxShared=1; Platform: x64
* comp=140, xp=_xp, wxShared=1; Platform: Win32
* comp=120; Platform: x64
* comp=120; Platform: Win32
* comp=120, wxShared=1; Platform: x64
* comp=120, wxShared=1; Platform: Win32
* comp=120, xp=_xp; Platform: x64
* comp=120, xp=_xp; Platform: Win32
* **comp=120, xp=_xp, wxShared=1; Platform: x64**
* **comp=120, xp=_xp, wxShared=1; Platform: Win32**

**Comment by slodki** [comment]
@stef145g You must use [BUILD.md](https://github.com/slodki/moneymanagerex/blob/update-cmake2/BUILD.md) instructions to build on Windows. You missed step about Developer Command Prompt. If you follow these instructions it will build correctly. I've tested this PR on my PC before submitting.
There is nothing to correct.

In the VS IDE you have 2 options:
1. Build Solution to compile and install in right directories all required files
2. Build mmex to compile and update in right directories executable only.
This is standard VS workflow to rebuild all/selected targets/projects/components. We don't need additional non-standard option for this IMHO.

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 6142c1f1599e0d0f0ee95c8f0c860a24cf812bfe
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 97f99dd907dfec06aac10c7f577d4fbe56643ebd
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 0da272dcd1d09d8e0b9fca1fe015384109b9cca3
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 47179e23b8a55252e41af71313fe4d24d52f8ec2
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
