### PR TITLE
feat(#1477): nested categories

### PR DESCRIPTION
**Pull request by n-stein**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5347)

### CODE REVIEW

**Comment by whalley** [comment]
@n-stein The CI build fails because it runs the scripts to generate headers itself (the generated code is in the repo for people who just build from that). Need to update the database submodule. 

Also a few SCA highlights that may need looking at.

**Comment by n-stein** [comment]
> Also a few SCA highlights that may need looking at.

Fixed

**Comment by whalley** [comment]
@n-stein Now we have the latest wxSQLite3 running on all platforms... Do you want to update the database sub-module to pull in the latest version and add to this PR?  This should fix the CI builds. We can then merge it ready for wider testing.

**Comment by n-stein** [comment]
> Do you want to update the database sub-module to pull in the latest version and add to this PR?

Done

**Comment by n-stein** [comment]
@whalley 
Let me do a PR for the GRM updates, then we can update that submodule here too.

**Comment by n-stein** [comment]
moneymanagerex/general-reports#77 opened

**Comment by n-stein** [comment]
I think we've updated all required submodules. Ready to merge.

**Comment by n-stein** [comment]
Seems to be a file missing from a prior pull request moneymanagerex/general-reports#75

**Comment by n-stein** [comment]
Updated general-reports submodule, Hopefully build is successful now.

**Comment by whalley** [comment]
@n-stein Couple of casts need sorting for Linux build...
https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/207/workflows/b2dc0f2e-392b-4f15-876b-7e9e83b556c0/jobs/206
Probanly want to add these checks to the Win build to make it a bit stricter.

**Comment by n-stein** [comment]
@whalley 

Thanks, sorted in PR #5362. No need to relax the Linux builds, its ME who needs to be stricter!

**Pull request merged**
