### PR TITLE
SUID support

### PR DESCRIPTION
**Pull request by guanlisheng**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6964)

### CODE REVIEW

**Comment by whalley** [comment]
@guanlisheng I presume we no longer need this PR?

**Comment by guanlisheng** [comment]
hi @vomikan, @whalley , @n-stein ,can you take a look 

we can step to SUID now after #6965 is done

**Comment by georgeef** [comment]
The SUID is of little interest to the user because it is too long to remember, however SUIDs are monotonic in time, so sorting by SUID is the same as sorting by time of creation. Old ID's are small numbers and have been created before the introduction of SUID, so they are also sorted by time of creation.

**Proposal:** instead of the ID (SUID), show the sequence number, starting from 1 for the first item in the list and incremented by 1 for each next item, with a label like `#` or `S/N`.

**Comment by whalley** [comment]
> **Proposal:** instead of the ID (SUID), show the sequence number, starting from 1 for the first item in the list and incremented by 1 for each next item, with a label like `#` or `S/N`.
> 
> 
> 
> The ID can be a separate column, which is hidden by default.

That would work, but suspect we don't need to display the ID as we don't display for any other tables and may confuse. Perhaps we just replace display of ID by the sequence number.

**Comment by whalley** [comment]
Can change DB SELECT queries to do an SQL RANK to generate the sequence number...

E.g. `SELECT *,  RANK () OVER (ORDER BY TRANSID ASC) SEQNO FROM CHECKINGACCOUNT_V1;`

I'm not very good with Python and it will need tweaks to the `sqlite2cpp.py` to add this for the tables.

**Comment by georgeef** [comment]
Maybe you don't need DB support to assign sequence numbers, you can do it on the fly when you generate the list of items to be displayed. If they are stored in a table, the sequence number is the table index plus 1. If there are more items in the table (like executions of scheduled transactions), you can add an additional field for the sequence number in an auxiliary table and fill it in on the fly. 

Or you may assign sequence numbers also to scheduled executions. But you need to distinguish between transactions and scheduled executions in the panels, I did this by showing an empty ID field for scheduled executions.

The sequence number is not a sticky information applied to a transaction. Different filters or even a redraw may assign different sequence numbers. It is just a visual aid to the users and a handle to sort by time of creation, but its value is actually opaque.

**Comment by georgeef** [comment]
My proposal was to assign sequence numbers when the list is generated, and to preserve them until a new list is generated. Sorting by another column of course does not change the sequence numbers. So in this respect a sequence number behaves like a temporary ID.

Sorry for not being very clear in my first proposal.

**Comment by georgeef** [comment]
By the way, for almost all (I think for all) other tables, there is no need to display the ID or a sequence number, because they have either a unique key which is more important, or other fields which are sufficient for ordering.

In transaction panels, the ID is essentially used as a substitute for a missing time-of-creation field. There is a date field, but it is not enough for sorting by time of creation.

**Comment by georgeef** [comment]
I think you need to store the sequence number in a separate field, you cannot just overwrite the ID (SUID) with a sequence number in the list of transactions. If the user wants to edit or process an item in the list, then you need the ID of this item in order to interact with DB.

**Comment by whalley** [comment]
> I think you need to store the sequence number in a separate field, you cannot just overwrite the ID (SUID) with a sequence number in the list of transactions. If the user wants to edit or process an item in the list, then you need the ID of this item in order to interact with DB.

Agreed, my original thought was to generate a sequence number in addition to all the 'real' DB fields (including ID) hence the SQL RANK(). But as you note we only really need this for the one table view so perhaps we just code for it there.

**Comment by georgeef** [comment]
@whalley 
Since the display of ID is under revision, I have a relevant question/request.

`TransactionListCtrl::OnColClick` forces the secondary sort column to be ID when the primary is Date. This is sometimes annoying, because there is no way to sort by Date/Number or any pairing with Date.

Could we remove this restriction, so the user can select any secondary together with Date, like in all other cases?  Or if Date/ID is often needed, could we assign it to a modifier-key + click on Date?

**Comment by whalley** [comment]
> @whalley Since the display of ID is under revision, I have a relevant question/request.
> 
> `TransactionListCtrl::OnColClick` forces the secondary sort column (`prev_g_sortcol`) to be ID when the primary (`g_sortcol`) is Date. This is sometimes annoying, because there is no way to sort by Date/Number or any other pairing with Date.
> 
> Could we remove this restriction, so the user can select any secondary together with Date, like in all other cases? Or if Date/ID is often needed, could we assign it to a modifier-key + click on Date?

There is discussion on this here: https://github.com/moneymanagerex/moneymanagerex/issues/4690

**Comment by guanlisheng** [comment]
guys, how about this PR itself?

**Comment by guanlisheng** [comment]
I'm going to merge it if there is no other objection. 

Large id would be from mobile devices as sync data is common.

**Comment by georgeef** [comment]
@whalley, @guanlisheng
I can implement sequence numbers in transaction panels, unless you already work on it. I estimate about 1 day.

**Comment by whalley** [comment]
> @whalley, @guanlisheng I can implement sequence numbers in transaction panels, unless you already work on it. I estimate about 1 day.

Go for it. I've got used to the large transaction IDs now :-) But it would be a good usablility feature to have the sequence number.

**Comment by n-stein** [comment]
Is there a way the sequence number can be derived based on transaction data? It would be good to have a calculated sequence number that provides consistency, otherwise it might be confusing if the same transaction had a different sequence number in the account view, account group view, all transactions view, and transaction report.

**Comment by georgeef** [comment]
The idea is that the sequence number is only a placeholder for sorting purposes, and its value is of no interest. It is not any kind of identification and it is not sticky (it may change at every refresh). In my proposal above it is created on the fly each time a panel is created or refreshed.

Essentially it is used instead of the creation datetime. In other panels and reports the ID is also not included.

The main problem in the identification of transactions is that they don't have a unique key. Even if time is enabled, the DB does not guarantee unique datetime. ID is now way too long to be useful for this purpose.

For cross reference between panels/reports, it is maybe more convenient to have some kind of hyperlinks, instead of asking users to memorize IDs.

**Comment by georgeef** [comment]
I think it is better to have both the ID and SN as separate columns. The users can choose which one to keep and which to hide.

**Comment by rmelillo76** [comment]
@georgeef - thoughts on changing the column header text from "SN" to "Sequence #" or just "#" instead? I realize "SN" is Sequence Number, but it may not be obvious to most users. The # is generally known as the number sign.

For example, we do this on the Import dialog to number the transactions:
image

**Comment by georgeef** [comment]
This was one of the options, it also has the big advantage that it doesn't need translation. On the other hand # doesn't look so nice in the sort indicator and SN is more symmetric to ID. # could be confusing, it might be interpreted as ID, maybe it is used already with different meaning somewhere else.
At the end I decided to use the more descriptive name SN. The meaning can be explained in a tooltip.

**Comment by georgeef** [comment]
Added a tip for SN in #7095.

**Pull request merged**
