### PR TITLE
fix(#5410): common translations of UI languages

### PR DESCRIPTION
**Pull request by n-stein**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6171)

### CODE REVIEW

**Comment by n-stein** [comment]
This requires at least CMake version 3.18, but the AppVeyor build system is running 3.16.2. Current stable version is 3.27.2.

@vomikan @whalley Any objections to updating to the latest stable release of CMake?

**Comment by vomikan** [comment]
> Is there a reason we are still using 2017?

Nothing obliges us not to upgrade.

**Comment by whalley** [comment]
Actually looking at CircelCI builds
https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/906/workflows/779f2914-cac1-4e23-bf23-d9158b8d7529/jobs/903

- Tumbleweed is 3.24.1
- Jammy 3.22.1
- Focal 3.16.3
- Bionic 3.10.2
- Fedora 36 3.22.2

**Comment by n-stein** [comment]
Closed in favor of #6172

**Pull request closed without merging**
