### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by ovari**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7054)

### CODE REVIEW

**Comment by ovari** [comment]
@n-stein unfortunately all was not done

**Comment by n-stein** [comment]
I fixed that 'and more…' in #7055 since that is the only one that doesn't require retranslation on Crowdin.

**Comment by ovari** [comment]
> I fixed that 'and more…' in #7055 since that is the only one that doesn't require retranslation on Crowdin.

Thank you. Have updated https://github.com/moneymanagerex/moneymanagerex/pull/7054 to remove that string.

**Comment by ovari** [comment]
@n-stein Thank you for your comment at https://github.com/moneymanagerex/moneymanagerex/pull/7057#issuecomment-2560639809. Updated this PR with your comment. Thank you once again.

**Pull request merged**
