### PR TITLE
perf(#906): speedup, cache

### PR DESCRIPTION
**Pull request by vomikan**
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/916)

### CODE REVIEW

**Comment by guanlisheng** [comment]
i think it's invalid as current performance is pretty okay in mac platform. would you mind to provide some proof here to tell the wxDate is the bottleneck.

**Comment by vomikan** [comment]
It's a final changes to avoid date parsing and cleanup.
I think it may be accepted.

**Comment by stef145g** [comment]
I will test this before accepting this

**Comment by guanlisheng** [comment]
Thanks and we may test whether it will improve the performance 

 
Thanks
Lisheng 

Sent from mobile

**Comment by stef145g** [comment]
mmex_tests used to test performance of patch. Tests builds without patch and with patch, created.
Comparing runs for each build and looking at times for: Account View: xx 
Each run produces different times, depending on other process from CPU
Tests can be built using mmex_texts update (#922)

**Comment by guanlisheng** [comment]
And what's the result for the performance test?seems you just merged the patch

**Comment by stef145g** [comment]
Tests were acceptable so I merged the patch.
Tests updated in order to allow others to build and get test results on their machines.

**Comment by stef145g** [comment]
I am also using my updated build with my data at present.

**Comment by guanlisheng** [comment]
The question is whether there is any runtime number here to tell us that It does improve the performance

**Pull request merged**
