### PR TITLE
feat(Stock.and.Asset.Transfer.Transactions): provision of new features

### PR DESCRIPTION
**Pull request by stef145g**
New features:
- New: Asset Accounts
- New: Asset transfers from/to normal accounts 
- NEW: Asset Transactions
- New: Loan Accounts
- New: Share Accounts
- New: Share transfers from/to normal accounts 
- New: Buying and Selling of Shares
- New: Record Share dividends
- Updated documentation for Shares

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 418596a127fc0cc202162570fa37db7f914cf8e6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: f14f34e4072f7758ef5096c5d8cad3e92104453f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: ce4a6aae6c2b2c344e27a0d24128583af470c8c0
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format**

 * Commit: 77ff6dfe611b76f65d795402781672e96fe00cf2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 81c6969faee53d8e0f4f380963a62424463b0f41
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: f088fb9aaf466195801bf869ad9bafff41ecd971
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: b082679d0dbaab5bb43ff89704c7972075db0687
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 418596a127fc0cc202162570fa37db7f914cf8e6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: f14f34e4072f7758ef5096c5d8cad3e92104453f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: ce4a6aae6c2b2c344e27a0d24128583af470c8c0
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format**

 * Commit: 77ff6dfe611b76f65d795402781672e96fe00cf2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 81c6969faee53d8e0f4f380963a62424463b0f41
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: f088fb9aaf466195801bf869ad9bafff41ecd971
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: b082679d0dbaab5bb43ff89704c7972075db0687
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by guanlisheng** [comment]
I knew you have spent much time on this change while I still don't think it's correct

**Comment by stef145g** [comment]
I didn't use the asset recording before, but the new feature has opened up more possibilities6. Associating these with loans will definitely make it useful.

One of my all time bug bares for me, was the fact MMEX could not successfully manage shares and dividends. I have finally been able to solve this problem, and I am now successfully using my new features, thus the reason for the pull request.

The pull request also gives other developers a chance to explore and evaluate the new features.

**Comment by vomikan** [comment]
@stef145g Somthing like this should be implemented in future. But not for 1.3.0.
I don't like that we have separate view for Assets and Transfers. The same issue for Stocks.

**Comment by stef145g** [comment]
Merge conflicts resulting from subsequent commits to master.
Closing, because this can not be merged in this state.

**Pull request closed without merging**
