### PR TITLE
Have license.txt be translatable

### PR DESCRIPTION
**Pull request by joshua-stone**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6283)

Fixes https://github.com/moneymanagerex/moneymanagerex/issues/6269

### CODE REVIEW

**Comment by joshua-stone** [comment]
@ovari I believe you'll be able to add translations for https://github.com/moneymanagerex/moneymanagerex/issues/6269 once this is merged

**Comment by ovari** [comment]
Thank you @joshua-stone.

Will the translations be in [Crowdin](https://crowdin.com/project/moneymanagerex)?

Thank you once again

**Comment by joshua-stone** [comment]
@ovari I'm not sure. As I understand it, this change will allow for a separate translation of `license.txt` and `contrib.txt` to be placed in [docs/mmex/help/$LOCALE/](https://github.com/moneymanagerex/moneymanagerex/tree/master/docs), otherwise MMEX will fall back to `doc/mmex/help/`

**Comment by joshua-stone** [comment]
@ovari @whalley Is there anything else needed for this to be merged?

**Comment by whalley** [comment]
My concern with this is that these files are processed in 'aboutdialog.cpp' to seperate detail for the the About dialog. Any 'corruption' made whilst translating the file and not maintaining the required delimitors may cause issues.  Much of Contrib.txt probably does not required conversion. Just a few thoughts.

**Comment by joshua-stone** [comment]
> My concern with this is that these files are processed in 'aboutdialog.cpp' to seperate detail for the the About dialog. Any 'corruption' made whilst translating the file and not maintaining the required delimitors may cause issues. Much of Contrib.txt probably does not required conversion. Just a few thoughts.

That's an understandable concern.

When I was investigating options for translations, I had noticed that localized text files were already controlled in [`docs/`](https://github.com/moneymanagerex/moneymanagerex/tree/master/docs). having a separate license.txt file for each translation seems like a good fit there.

**Comment by ovari** [comment]
How can this be translated? Thank you

**Comment by joshua-stone** [comment]
@ovari I think contributors have to do the following:

1) Copy [`license.txt`](https://github.com/moneymanagerex/moneymanagerex/blob/master/license.txt) to [`docs/$LOCALE/license.txt`](https://github.com/moneymanagerex/moneymanagerex/tree/master/docs)
2) Translate `license.txt` to their respective language
3) Add the translated `license.txt` in a PR.

**Pull request merged**
