### PR TITLE
fix(#7055): fix translations with unicode

### PR DESCRIPTION
**Pull request by n-stein**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/7057)

### CODE REVIEW

**Comment by n-stein** [comment]
@ovari fyi -- including unicode symbols in translatable strings doesn't work unless you wrap them properly.

`_("text with unicode…")` 

should be changed to

`wxGetTranslation(wxString::FromUTF8(wxTRANSLATE("text with unicode…")))`

**Comment by georgeef** [comment]
@n-stein 
Can we add a macro to make it short, e.g., `_u("text with unicode…")`?

**Comment by n-stein** [comment]
Yes, good idea. I'll work on that.

**Comment by ovari** [comment]
> > @n-stein Can we add a macro to make it short, e.g., `_u("text with unicode…")`?
> 
> I've added a macro in #7121
> 
> `wxGetTranslation(wxString::FromUTF8(wxTRANSLATE(unicode_string)))` can now be written `_u(unicode_string)`
> 
> @ovari please use this shortened form in #7072

Done.

**Pull request merged**
