### PR TITLE
fix(#3527): #3510

### PR DESCRIPTION
**Pull request by vomikan**
make sure your code would work on both windows, linux and osx

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 7c84ad2bd57bdee07ca0cb30e84037fc54f5199d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: db156664b84a6ee9cacc12d121c15c0a61abc4bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by whalley** [comment]
@vomikan - Not sure why the colors have been changed to being mandatory in the theme. If they are mandatory then we should also set the color to "" as a default means nothing if it is mandatory. The fact they are optional means the application default will be used if not defined in the theme.  

Am I missing something here?

**Comment by vomikan** [comment]
The solution is this. If an empty value is set for the panel color, then do not apply the color. Since the colors are not set in the JSON file, they must be taken from the list of default values.

**Comment by whalley** [comment]
So, original intended logic was...

If the metadata item was marked as "MANDATORY" then it **must** be defined in the theme JSON, so the default value was meaningless as it would always be taken from the theme JSON.

If the metadata item was **not** marked as "MANDATORY" then if it is defined in the theme JSON this value will be used. If it was not defined in the theme JSON then the application default will be used.

So code such as:
`md[COLOR_LISTALT0]         = std::make_tuple("/colors/listAlternative1", "#F0F5EB", true);`

should be:
`md[COLOR_LISTALT0]         = std::make_tuple("/colors/listAlternative1", "", true);`

As the data should be mandatory in the theme JSON.

**Comment by vomikan** [comment]
Thank you for the clarification.
I need to think about whether there was a logical error after my changes.

My idea is as follows. The value can be set in a JSON file, even empty. If the value is empty, then it should be ignored (not applied to the UI object). But if it is REQUIRED, then find the corresponding value from the default list.
If the value is not set in the JSON file, we take the default value.

**Comment by vomikan** [comment]
If you clearly see how to fix the code, please do so.

**Comment by whalley** [comment]
I was not aware it was broken :-) Will have look later.

**Comment by whalley** [comment]
Reverting the changes you made makes no difference. It worked fine without the changes you made.

**Comment by whalley** [comment]
Actually ignore above... There does seem to be an issue.

**Pull request merged**
