### PR TITLE
Create org.moneymanagerex.MMEX.metainfo.xml

### PR DESCRIPTION
**Pull request by ovari**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

https://github.com/flathub/flathub/pull/4184#discussion_r1209315320

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5950)

### CODE REVIEW

**Comment by joshua-stone** [comment]
This looks good to me. The added changelog information and translations are a nice touch!

**Comment by joshua-stone** [comment]
Upon further investigation, it would appear that this doesn't pass validation:

```
$ appstreamcli validate --strict --pedantic org.moneymanagerex.MMEX.metainfo.xml
P: org.moneymanagerex.MMEX:3: cid-contains-uppercase-letter org.moneymanagerex.MMEX
W: org.moneymanagerex.MMEX:~: category-invalid accounts
W: org.moneymanagerex.MMEX:~: category-invalid accounting
W: org.moneymanagerex.MMEX:~: category-invalid finance
W: org.moneymanagerex.MMEX:~: category-invalid money
W: org.moneymanagerex.MMEX:~: category-invalid productivity
```

The list of valid categories can be found here:

https://specifications.freedesktop.org/menu-spec/latest/apa.html

These lines appear to work:

```xml
  <categories>
    <category>Finance</category>
  </categories>
```

**Comment by ovari** [comment]
@joshua-stone added a few more categories in alphabetically order. Can you please add to your patch to see that they work?

```
  <categories>
    <category>Education</category>
    <category>Finance</category>
    <category>Office</category>
  </categories>
```

Thank you

**Comment by ovari** [comment]
@joshua-stone also added some full-stops if you can please add them to your file. Thank you

**Comment by ovari** [comment]
@joshua-stone Please take over this pull request. Please change and update anything that needs to be done to the pull request. Thank you

**Comment by joshua-stone** [comment]
> @joshua-stone also added some full-stops if you can please add them to your file. Thank you

Done!



> @joshua-stone Please take over this pull request. Please change and update anything that needs to be done to the pull request. Thank you

I don't think much more needs to be done with this pull request as it's just to include a new file in upstream MMEX repo instead of the downstream flatpak repo. For now it can reside in `resources/org.moneymanagerex.MMEX.metainfo.xml` so as to fulfill the recommendation to upstream this file. Any more changes can be done in a separate PR.

**Pull request closed without merging**
