### PR TITLE
Add NEWS file to track changes across versions

### PR DESCRIPTION
**Pull request by joshua-stone**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

This will help address the version mismatch issue pointed out in https://github.com/moneymanagerex/moneymanagerex/issues/6246

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6250)

### CODE REVIEW

**Comment by joshua-stone** [comment]
@whalley This can be the start of having a single source-of-truth for where builds will derive version information as well as let us prepare release notes ahead of time.

**Comment by whalley** [comment]
> @whalley This can be the start of having a single source-of-truth from where builds derive version information as well as let us prepare release notes ahead of time.

We already have the single source of truth in the CMakeLists file....

**Comment by joshua-stone** [comment]
> > @whalley This can be the start of having a single source-of-truth from where builds derive version information as well as let us prepare release notes ahead of time.
> 
> We already have the single source of truth in the CMakeLists file....


> > @whalley This can be the start of having a single source-of-truth from where builds derive version information as well as let us prepare release notes ahead of time.
> 
> We already have the single source of truth in the CMakeLists file....
> 
> Also release notes are held against each release in GitHub https://github.com/moneymanagerex/moneymanagerex/releases
> 
> So this file is actually a duplicate of information we already have. As I have noted before, if we need this for Flathub then we should generate it from the existing info.

The point of this change is to shift to using a machine-readable format as a canonical source of truth so that the rest of the tools can easily consume it. The changes include having CMakeLists generate version info from the NEWS file.

As for release notes against each release on Github, the formatting has changed over time and hasn't been consistent. For example, the latest release there isn't even a handwritten changelog:

https://github.com/moneymanagerex/moneymanagerex/releases/tag/v1.6.4

By writting release information in the NEWS file, you can simply copy notes into the release notes for a tagged Github release on the releases page while making sure the notes are formatted neatly.

**Comment by whalley** [comment]
The existing CMAKE numbering has rigid structure for identifying the beta/alpha/rc releases where the NEWS.md file does not. I'm just a little concerned about changing the process we use for identifying build numbers and publishing the release notes. Yes, the last release notes just linked to the Issue list for that release but that seems sufficient. 

We have scare resource to maintain the product as it is and wanted to avoid intoroducing some additonal maintenance with new releases. I'll let others comment further.

**Comment by joshua-stone** [comment]
> The existing CMAKE numbering has rigid structure for identifying the beta/alpha/rc releases where the NEWS.md file does not. I'm just a little concerned about changing the process we use for identifying build numbers and publishing the release notes. Yes, the last release notes just linked to the Issue list for that release but that seems sufficient.
> 
> We have scare resource to maintain the product as it is and wanted to avoid intoroducing some additonal maintenance with new releases. I'll let others comment further.

The NEWS format might be more free-form than CMakeLists, but that doesn't mean it's without structure. The `appstreamcli` utility will still fail if it detects malformed input, which is something you'd want to discover early during the development process:

```
$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Checking for one of the modules 'libcurl'
-- Found CURL: /usr/lib64/libcurl.so (found version "8.0.1")
-- Module support is disabled.
-- Version: 8.1.1
-- Build type: 
-- CXX_STANDARD: 11
-- Required features: cxx_variadic_templates
-- Found RapidJSON: /var/home/jstone/Work/github/joshua-stone/moneymanagerex/3rd/rapidjson/include
-- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
Unable to parse NEWS header 'Versiion 1.7.0
~~~~~~~~~~~~~
Released: 2023-10-19': Unable to find version in: Versiion 1.7.0
~~~~~~~~~~~~~
Released: 2023-10-19
CMake Error at CMakeLists.txt:648 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"



-- Configuring incomplete, errors occurred!
```

It's simply easier for humans to update a text file so that tools can know here to look for generating output:

https://gist.github.com/joshua-stone/506800597626d0a9705fe0feade32211

I understand that this may seem like extra work for a new release, but the recurring issue we've had is syncing up version information across files because the metainfo file doesn't stay up to date, which is what this change is intended to address.

Updating a NEWS file and using it as a single source-of-truth for combining with a metainfo file while minimizing duplication.

**Comment by whalley** [comment]
Alpha/Beta/RC releases can have versions. 

E.g 
1.7.0 Beta 1
1.7.0 Beta 2

**Comment by joshua-stone** [comment]
> Alpha/Beta/RC releases have versions.
> 
> E.g 1.7.0 Beta 1 1.7.0 Beta 2

It should follow it more closely now:

```
$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Build type: Beta
-- Checking for one of the modules 'libcurl'
-- Found CURL: /usr/lib64/libcurl.so (found version "8.0.1")
-- Module support is disabled.
-- Version: 8.1.1
-- Build type: 
-- CXX_STANDARD: 11
-- Required features: cxx_variadic_templates
-- Found RapidJSON: /var/home/jstone/Work/github/joshua-stone/moneymanagerex/3rd/rapidjson/include
-- Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:778 (message):
  Unknown Linux distribution - generating generic package.


-- 
-- MMEX configuration summary
-- ==========================
-- Version        : 1.7.0-Beta.1
-- Commit         : 253f9721d (2023-10-20)
-- Branch         : news-file
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : 
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 6.5.6-200.fc38.x86_64
-- Fedora Linux.38 (Container Image)
-- 
-- CMake 3.27.7
-- GNU Make 4.4
-- ccache
-- GNU 13.2.1
-- wxWidgets 3.2.2
-- wxSQLite3 4.9.1
-- Lua 5.3.5
-- curl 8.0.1
-- gettext 0.21.1
-- ------------------ 8< -----------------
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /var/home/jstone/Work/github/joshua-stone/moneymanagerex/build
```

**Comment by whalley** [comment]
One, probably, final question.

What date should be reflected in the NEWS file for development/beta releases? E.g. 1.7.0 Beta 1 will be regularly updated as we merge commits. At present it would likely by updated with the date when we first named the Beta 1 release.

**Comment by joshua-stone** [comment]
> One, probably, final question.
> 
> What date should be reflected in the NEWS file for development/beta releases? E.g. 1.7.0 Beta 1 will be regularly updated as we merge commits. At present it would likely by updated with the date when we first named the Beta 1 release.

I think what date to pick for a given release depends on the type of release. i.e., it can either reflect the time of branching a development release or the time of tagging a new stable release. Frequently updating the date string for a development cycle wouldn't be very useful since the point of a date string is to track a point in time and the changes that've been made since that point.

For example, a Beta release would have the time that development started, which gets more notes added to it as time goes on: 

```
Version 1.7.0 Beta 1
~~~~~~~~~~~~~~~~
Released: 2023-10-19

Bugfixes:
* Fix 1
* Fix 2
```

.. Eventually having:

```
Version 1.7.0 Beta 1
~~~~~~~~~~~~~~~~
Released: 2023-10-19

Bugfixes:
* Fix 1
* Fix 2
* Fix 3
* Fix 4
```

And then when it comes time to [tag a new release](https://github.com/moneymanagerex/moneymanagerex/tags), make sure to update NEWS with a version entry that reflects the tagged version on Github:

```
Version 1.7.0
~~~~~~~~~~~
Released: 2023-10-21
```

Does that make sense?

**Comment by whalley** [comment]
Yes fair enough...

**Comment by joshua-stone** [comment]
Ultimately I think how MMEX team wants to update the NEWS file is going to be a matter of preference, but I think having a file dedicated to storing a history of release versions, release types, release dates, and release changes is going to be more flexible than periodically incrementing a few hardcoded values in CMakeLists.txt. It also gives contributors the opportunity to prepare release notes like how they can update README.md.

Are there any changes I should make here?

**Comment by joshua-stone** [comment]
Looks like these [built successfully](https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/1008/workflows/8de59fdd-7940-4691-b19a-d06fff73c80f/jobs/1005):

```
$ flatpak info org.moneymanagerex.MMEX//master

MMEX Money Manager - Organize finances and track cash flow

          ID: org.moneymanagerex.MMEX
         Ref: app/org.moneymanagerex.MMEX/x86_64/master
        Arch: x86_64
      Branch: master
     Version: 1.7.0 Beta 1
     License: GPL-2.0-only
      Origin: mmex-origin
  Collection: 
Installation: system
   Installed: 39.1 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: 83d06d74061578b159ca8a9502fa511848747f65701989beb3a6ca5c8cf441ba
     Subject: Export org.moneymanagerex.MMEX
        Date: 2023-10-21 23:01:52 +0000
```

image

**Comment by joshua-stone** [comment]
Thanks you for merging!

**Pull request merged**
