### PR TITLE
fix(Import.CSV): more fields for ignore

### PR DESCRIPTION
**Pull request by vomikan**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d247f80bf07f0e203f838cc9e62faf66cc277f55
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d247f80bf07f0e203f838cc9e62faf66cc277f55
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d247f80bf07f0e203f838cc9e62faf66cc277f55
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d247f80bf07f0e203f838cc9e62faf66cc277f55
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by guanlisheng** [comment]
Why we have a magic number 99?

**Comment by vomikan** [comment]
Becouse I can't make while (last element of JSON object)

2015-01-13 7:37 GMT+03:00 Lisheng <notifications@github.com>:

**Comment by guanlisheng** [comment]
I will merge it soon while better to remove this magic number soon as well.

**Pull request merged**
