### PR TITLE
fix(#4216): v1.6.0 Beta.1 WARNING DB UPGRADE

### PR DESCRIPTION
**Pull request by whalley**
**WARNING THIS UPGRADES THE DB.**
**WARNING THIS UPGRADES THE DB.**
**WARNING THIS UPGRADES THE DB.**

 I'VE ALREADY TESTED IT AS MUCH AS I CAN AND CANT SEE ANYTHING OBVIOUSLY BROKEN. PLEASE TEST BEFORE MERGING TO MASTER

Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141)

### CODE REVIEW

**Review by tactilis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141)* status: 0 of 59 files reviewed, 7 unresolved discussions (waiting on @tactilis and @whalley)

___
*[`src/billsdepositsdialog.cpp` line 1016 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND72gF83MA413eNUiyN:-ND72gF83MA413eNUiyO:b-2nuhi1) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/billsdepositsdialog.cpp#L1016)):*
> ```cpp
>     const Model_Account::Data* toAccount = Model_Account::instance().get(m_bill_data.TOACCOUNTID);
>     if (m_bill_data.TRANSDATE < account->INITIALDATE)
>         return mmErrorDialogs::ToolTip4Object(cbAccount_, _("The opening date for the account is greater than the date of this transaction"), _("Invalid Date"));
> ```

Would be better as:

"The opening date for the account is later than the date of this transaction"

earlier/later than for dates
less/greater than for quantities



_Code quote:_
```cpp
"The opening date for the account is greater than the date of this transaction"
```
___
*[`src/stockdialog.cpp` line 428 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74Sdo76syTeM4TmaW:-ND74Sdp2ayaY4Gi8R4D:b-qidhnw) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/stockdialog.cpp#L428)):*
> ```cpp
>     const wxString pdate = m_purchase_date_ctrl->GetValue().FormatISODate();
>     if (pdate < account->INITIALDATE)
>         return mmErrorDialogs::ToolTip4Object(m_purchase_date_ctrl, _("The opening date for the account is greater than the date of this transaction"), _("Invalid Date"));
> ```

Would be better as:

"The opening date for the account is later than the date of this transaction"



_Code quote:_
```cpp
"The opening date for the account is greater than the date of this transaction"
```
___
*[`src/transdialog.cpp` line 576 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74cRi2HXArUd7eTIN:-ND74cRi2HXArUd7eTIO:b-qidhnw) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/transdialog.cpp#L576)):*
> ```cpp
>     if (m_trx_data.TRANSDATE < account->INITIALDATE)
>     {
>         mmErrorDialogs::ToolTip4Object(cbAccount_, _("The opening date for the account is greater than the date of this transaction"), _("Invalid Date"));
> ```

Would be better as:

"The opening date for the account is later than the date of this transaction"



_Code quote:_
```cpp
"The opening date for the account is greater than the date of this transaction"
```
___
*[`src/transdialog.cpp` line 651 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74gHm-nN77KKF7n4_:-ND74gHm-nN77KKF7n4a:b-qidhnw) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/transdialog.cpp#L651)):*
> ```cpp
>         if (m_trx_data.TRANSDATE < to_account->INITIALDATE)
>         {
>             mmErrorDialogs::ToolTip4Object(cbToAccount_, _("The opening date for the account is greater than the date of this transaction"), _("Invalid Date"));
> ```

Would be better as:

"The opening date for the account is later than the date of this transaction"



_Code quote:_
```cpp
"The opening date for the account is greater than the date of this transaction"
```
___
*[`src/usertransactionpanel.cpp` line 432 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74l6B8EEpv7vsomKU:-ND74l6B8EEpv7vsomKV:b-qidhnw) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/usertransactionpanel.cpp#L432)):*
> ```cpp
>     if (trxDate < account->INITIALDATE)
>     {
>         mmErrorDialogs::ToolTip4Object(m_account, _("The opening date for the account is greater than the date of this transaction"), _("Invalid Date"));
> ```

Would be better as:

"The opening date for the account is later than the date of this transaction"



_Code quote:_
```cpp
"The opening date for the account is greater than the date of this transaction"
```
___
*[`src/webapp.cpp` line 552 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74znB5IZlymhU2WWy:-ND74znB5IZlymhU2WWz:b-qidhnw) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/webapp.cpp#L552)):*
> ```cpp
>                             , _("Account"), accountName
>                             , _("Date"), trxDate
>                             , _("The opening date for the account is greater than the date of this transaction")
> ```

Would be better as:

"The opening date for the account is later than the date of this transaction"



_Code quote:_
```cpp
"The opening date for the account is greater than the date of this transaction"
```
___
*[`src/import_export/univcsvdialog.cpp` line 1050 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND7BBHt4vWxGsaQADPI:-ND7BBHt4vWxGsaQADPJ:b-qidhnw) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/import_export/univcsvdialog.cpp#L1050)):*
> ```cpp
>         {
>             wxString msg = wxString::Format(_("Line %ld: %s"), nLines + 1,
>                     _("The opening date for the account is greater than the date of this transaction"));
> ```

Would be better as:

"The opening date for the account is later than the date of this transaction"



_Code quote:_
```cpp
"The opening date for the account is greater than the date of this transaction"
```

**Comment by whalley** [comment]
@tactilis Will make the wording changes. Thanks for the suggestions.

**Review by whalley — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141)* status: 0 of 59 files reviewed, 7 unresolved discussions (waiting on @tactilis)

___
*[`src/billsdepositsdialog.cpp` line 1016 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND72gF83MA413eNUiyN:-ND82HfpEowKkgYq7lDA:b-896fix) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/billsdepositsdialog.cpp#L1016)):*
<details><summary><i>Previously, tactilis (Martin) wrote…</i></summary><blockquote>

Would be better as:

"The opening date for the account is later than the date of this transaction"

earlier/later than for dates
less/greater than for quantities
</blockquote></details>

Done.
___
*[`src/stockdialog.cpp` line 428 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74Sdo76syTeM4TmaW:-ND82KFo6uqeegzufLrp:b-896fix) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/stockdialog.cpp#L428)):*
<details><summary><i>Previously, tactilis (Martin) wrote…</i></summary><blockquote>

Would be better as:

"The opening date for the account is later than the date of this transaction"
</blockquote></details>

Done.
___
*[`src/transdialog.cpp` line 576 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74cRi2HXArUd7eTIN:-ND82M0X-4rZzvU8Aimh:b-896fix) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/transdialog.cpp#L576)):*
<details><summary><i>Previously, tactilis (Martin) wrote…</i></summary><blockquote>

Would be better as:

"The opening date for the account is later than the date of this transaction"
</blockquote></details>

Done.
___
*[`src/transdialog.cpp` line 651 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74gHm-nN77KKF7n4_:-ND82MelBv5bR4TVPqGC:b-896fix) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/transdialog.cpp#L651)):*
<details><summary><i>Previously, tactilis (Martin) wrote…</i></summary><blockquote>

Would be better as:

"The opening date for the account is later than the date of this transaction"
</blockquote></details>

Done.
___
*[`src/usertransactionpanel.cpp` line 432 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74l6B8EEpv7vsomKU:-ND82NbG3uSuD9lFTNWT:b-896fix) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/usertransactionpanel.cpp#L432)):*
<details><summary><i>Previously, tactilis (Martin) wrote…</i></summary><blockquote>

Would be better as:

"The opening date for the account is later than the date of this transaction"
</blockquote></details>

Done.
___
*[`src/webapp.cpp` line 552 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND74znB5IZlymhU2WWy:-ND82OSeDL0aQDer_NjJ:b-896fix) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/webapp.cpp#L552)):*
<details><summary><i>Previously, tactilis (Martin) wrote…</i></summary><blockquote>

Would be better as:

"The opening date for the account is later than the date of this transaction"
</blockquote></details>

Done.
___
*[`src/import_export/univcsvdialog.cpp` line 1050 at r1](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5141#-ND7BBHt4vWxGsaQADPI:-ND82PWM6oXXgV8_ePJ3:b-896fix) ([raw file](https://github.com/moneymanagerex/moneymanagerex/blob/564f265756c985ca79c6a17777751af1f262525c/src/import_export/univcsvdialog.cpp#L1050)):*
<details><summary><i>Previously, tactilis (Martin) wrote…</i></summary><blockquote>

Would be better as:

"The opening date for the account is later than the date of this transaction"
</blockquote></details>

Done.

**Comment by tactilis** [comment]
Looking at the code, I couldn't work out whether you had applied the `Opening Date > Transaction Date` check to all import paths:

image
 
  
Is WebApp handled?

**Comment by whalley** [comment]
> Is WebApp handled?

Yes. The change is in webapp.cpp

**Comment by whalley** [comment]
@tactilis Have you tested the new Beta2 version? Did the DB upgrade go OK?

**Comment by tactilis** [comment]
> @tactilis Have you tested the new Beta2 version? Did the DB upgrade go OK?

Yes. Tried it on a copy of my master database.
 
image

 
I've had a quick look and as far as I can see, all is OK - but not extensively tested yet.

Checked this, when trying to open DB with earlier MMEX:

image

All good so far.

**Comment by tactilis** [comment]
The creation of these may cause confusion for some people:
 
image
 
They will hang around for ever unless deleted by the user.

May not be a problem but just want to mention it here in case someone does a search for upgrade .bak files

**Comment by whalley** [comment]
> The creation of these may cause confusion for some people:
> 
> image
> 
> They will hang around for ever unless deleted by the user.
> 
> May not be a problem but just want to mention it here in case someone does a search for upgrade .bak files

Yes, normally you would just get the v7 as the backup prior to the upgrade taking place so that the user can revert (whether they did have backups on or not). Because of us upgrading to v15 (and skipping the aborted DB releases) the interim DBs are there by should still be identical to the v7 file. A bonus --- plenty of backups :-)

**Comment by whalley** [comment]
I've been using it on my main database for the past few days with no ill effects... So I'm not expecting any major to arise. Will probably merge the PR late this evening.

**Pull request merged**
