### PR TITLE
 fix(#659): ignore currency symbol

### PR DESCRIPTION
**Pull request by vomikan**
make sure your code would work on both windows, linux and osx

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 638dfd36f563977d710d064f1cfda1edd5e3ad7e
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by stef145g** [comment]
Checks show that branch is out of date, even though I can successfully merge this pull request.
Manual merging to upstream is prevented by checks.
@guanlisheng, Please investigate this problem.

**Comment by stef145g** [comment]
@vomikan, I suggest that you
1. switch to vomikan:#659 branch
2. merge upstream:master to this branch
3.commit the changes to your vomikan:#659 branch

This should resolve the "branch out of date" issue so the PR can be merged.

**Comment by vomikan** [comment]
Can't be merged right now? OK

2016-02-27 15:06 GMT+03:00 Stefano <notifications@github.com>:

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 638dfd36f563977d710d064f1cfda1edd5e3ad7e
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format, doc, clean**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by vomikan** [comment]
Done

**Comment by siena123** [comment]
Lines 180 and 181 should be removed. They are not used and are not needed.

+    wxChar *sep = 0;
+    wxNumberFormatter::GetThousandsSeparatorIfUsed(sep);

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 638dfd36f563977d710d064f1cfda1edd5e3ad7e
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format, doc, clean**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by stef145g** [comment]
Please update submodule database as follows:
1. git.exe checkout master --
2. git.exe pull -v --progress  "origin"
This will bring this submodule up to date

You will also need to update the branch as it has gone out of date again using the above procedure.
Commit your changes.

**Comment by gitys** [comment]
This solution does not work for me because the currency symbol does not exists in the currency database. I specifically am using ILS (₪) but judging by the "DB_Table_Currencyformats_V1.h" file, many other currencies are missing a symbol as well.
If this is going to be the preferred solution over https://github.com/moneymanagerex/moneymanagerex/pull/720, I think at least all currency symbols should be added to the DB. A possible source that looked good to me: http://www.fxexchangerate.com/currency-symbols.html

**Comment by stef145g** [comment]
@gitys Please create a new database, then compare the CURRENCYFORMATS_V1 table to your working database. You will need a program that you can examine the raw database file. This may shed more light to the final solution.

**Comment by gitys** [comment]
What program would you recommend for that?

**Comment by stef145g** [comment]
There are various programs available to examine the database outside of mmex.
One is wxSQLitePlus, https://github.com/guanlisheng/wxsqliteplus/releases but the one I use is sqlitebrowser https://github.com/sqlitebrowser/sqlitebrowser/releases

**Comment by stef145g** [comment]
A simpler way is to use mmex itself using the currency dialog.

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 638dfd36f563977d710d064f1cfda1edd5e3ad7e
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format, doc, clean**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gitys** [comment]
@stef145g, Thanks for the recommendation.
I installed SQLiteStudio and it actually looks like a really nice tool. If anyone is interested: [http://sqlitestudio.pl/?act=download](url)

I performed the requested test and results were as anticipated.
1. Without changing any code neither existing DBs nor new DBs have the Shekel symbol (₪)
2. If I add the symbol to the ensure_data() function, new DBs contain the symbol.

Note that I tested with a random character since ₪ is unicode and the source files that compile this are not currently unicode.

**Pull request merged**
