### PR TITLE
Attempt to correctly display localized `<description>` tags at Flathub

### PR DESCRIPTION
**Pull request by ovari**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

### README.TXT
1. Alphabetical by locale code
2. Add magyar

Can README.TXT be deleted as information is now contained in org.moneymanagerex.MMEX.metainfo.xml.in?

### org.moneymanagerex.MMEX.metainfo.xml.in

1. Attempt to correctly apply the localize <description> tag to show correctly at https://flathub.org/hu/apps/org.moneymanagerex.MMEX
2. Add <description> to other locales to attempt to show correctly at:
* https://flathub.org/de/apps/org.moneymanagerex.MMEX
* https://flathub.org/fr/apps/org.moneymanagerex.MMEX
* https://flathub.org/ru/apps/org.moneymanagerex.MMEX
* https://flathub.org/ta/apps/org.moneymanagerex.MMEX
* `https://flathub.org/<locale>/apps/org.moneymanagerex.MMEX`
3. Note that the captions on the screenshots at `https://flathub.org/<locale>/apps/org.moneymanagerex.MMEX` are only localized for hu (magyar - Hungarian). Perhaps localizing screenshot captions can be done once this pull request is merged.

Thank you

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6869)

### CODE REVIEW

**Comment by ovari** [comment]
@vomikan can you please review the Russian translation?

@joshua-stone @whalley can this please be merged before the 1.8.1 release to test the <description> tag for other locales?

After this pull request is merge and if there is time before the 1.8.1 release, perhaps could provide locales for screenshots captions too.

Thank you

**Comment by vomikan** [comment]
I've updated the pot file for https://crowdin.com/project/moneymanagerex

**Comment by ovari** [comment]
> I've updated the pot file for https://crowdin.com/project/moneymanagerex

Can you please update again as the new strings have been translated into Hungarian. Thank you

**Comment by whalley** [comment]
> > I've updated the pot file for https://crowdin.com/project/moneymanagerex
> 
> Can you please update again as the new strings have been translated into Hungarian. Thank you

Will pull latest translations in a few days to give others a chance to update other translations.

**Pull request merged**
