### PR TITLE
miscellaneous update

### PR DESCRIPTION
**Pull request by ovari**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6549)

### CODE REVIEW

**Comment by ovari** [comment]
1. Added keyboard shortcut
2. `vs.` American English.
`vs` Alternative form of [vs.](https://duckduckgo.com/?q=vs.+definition&ia=definition), often considered as [British English](https://duckduckgo.com/?q=British%20English+definition&ia=definition).
3. Removed space ` ` after `(` and space ` ` before `)` as source strings are English, not French.

**Comment by ovari** [comment]
@vomikan can you please review and merge this? Thank you

**Comment by vomikan** [comment]
> @vomikan can you please review and merge this? Thank you

Commit is not a problem. But this will delay the planned release.

**Comment by n-stein** [comment]
Just my two cents -- this seems like a lot of retranslation work to add a `.` to an already standard abbreviation. Seeing `vs` without the period wouldn't strike me as "not American English".

**Comment by ovari** [comment]
> Just my two cents -- this seems like a lot of retranslation work to add a `.` to an already standard abbreviation. Seeing `vs` without the period wouldn't strike me as "not American English".

This change also homogenizes "Vs" (starting with a capital letter) and "vs" (starting with a lowercase letter) to "vs.".

1. In [Microsoft language resources](https://learn.microsoft.com/en-us/globalization/reference/microsoft-language-resources), click "Microsoft UI String Search" in the [UI Strings](https://learn.microsoft.com/en-us/globalization/reference/microsoft-language-resources#ui-strings) section.
2. Enter "vs." in "Search source term" and press "Enter"
image

Hopefully this will help all the source strings in MMEX to be in correct according to the US English spelling style guide. It is understood that any change (however small) will creating more work for translators; however, it is expected that with time the strings will be homogenized.

> ## English (Australian) Dictionary
> image
> https://addons.thunderbird.net/thunderbird/addon/english-australian-dictionary/

**Comment by ovari** [comment]
> > @vomikan can you please review and merge this? Thank you
> 
> Commit is not a problem. But this will delay the planned release.

https://github.com/moneymanagerex/moneymanagerex/milestone/42 states "Past due by 22 days."

If the release is to be delay further, can this please be merged?

Or can the https://github.com/moneymanagerex/moneymanagerex/issues/6503 remaining open issue be resolved in the next release?

Thank you

**Pull request merged**
