### PR TITLE
feat(#4124):Duplicate recurring option

### PR DESCRIPTION
**Pull request by whalley**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/4125)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 294e2ebc691897f7c716a3728f2ce225a071a06a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 294e2ebc691897f7c716a3728f2ce225a071a06a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by tactilis** [comment]
@whalley 

In billsdepositspanel.cpp

```
billsDepositsListCtrl::OnItemRightClick(wxMouseEvent& event)

    menu.Append(MENU_TREEPOPUP_NEW, _("&New Recurring Transaction..."));
    menu.Append(MENU_TREEPOPUP_EDIT, _("&Edit Recurring Transaction..."));
    menu.Append(MENU_TREEPOPUP_DUPLICATE, _("Duplicate Recurring Transaction..."));  <<<<
    menu.Append(MENU_TREEPOPUP_DELETE, _("&Delete Recurring Transaction..."));
    menu.AppendSeparator();
    menu.Append(MENU_TREEPOPUP_ORGANIZE_ATTACHMENTS, _("&Organize Attachments"));
```

Duplicate Recurring Transaction is missing a keyboard shortcut. You used &u elsewhere for Duplicate

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 294e2ebc691897f7c716a3728f2ce225a071a06a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by whalley** [comment]
> @whalley
> 
> In billsdepositspanel.cpp
> 
> ```
> billsDepositsListCtrl::OnItemRightClick(wxMouseEvent& event)
> 
>     menu.Append(MENU_TREEPOPUP_NEW, _("&New Recurring Transaction..."));
>     menu.Append(MENU_TREEPOPUP_EDIT, _("&Edit Recurring Transaction..."));
>     menu.Append(MENU_TREEPOPUP_DUPLICATE, _("Duplicate Recurring Transaction..."));  <<<<
>     menu.Append(MENU_TREEPOPUP_DELETE, _("&Delete Recurring Transaction..."));
>     menu.AppendSeparator();
>     menu.Append(MENU_TREEPOPUP_ORGANIZE_ATTACHMENTS, _("&Organize Attachments"));
> ```
> 
> Duplicate Recurring Transaction is missing a keyboard shortcut. You used &u elsewhere for Duplicate

Added, thanks.

**Pull request merged**
