### PR TITLE
feat (ui.incexpenses): Add chart to current/last year 

### PR DESCRIPTION
**Pull request by mek-x**
Please look at my proposition of additional chart to "Income vs Expenses -> Current/Last Year" report

### CODE REVIEW

**Comment by guanlisheng** [comment]
hi @mek-x , i would like we can build this feature with HTML5 instead of the CPP. thought?

**Comment by mek-x** [comment]
hi @guanlisheng ! Yes, that's a good idea. You mean something similar to the homepage from #511 ?

**Comment by guanlisheng** [comment]
similar

**Comment by vomikan** [comment]
It should be used other style of coding: html template and js code.

**Pull request closed without merging**
