### PR TITLE
fix(#2066): theme splitter

### PR DESCRIPTION
**Pull request by whalley**
make sure your code would work on both windows, linux and osx

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3582)

### CODE REVIEW

**Comment by reddyshyam** [comment]
Is 1.6.0 not updated anymore? I am always on that stream

**Comment by whalley** [comment]
@reddyshyam At present the 1.5.3 version is tracking the master branch. So please use this as the latest version.

**Comment by reddyshyam** [comment]
Hi @whalley, thanks for the update but I am already on 1.6.0 stream, can I overwrite with 1.5.3 without any damage?

**Comment by vomikan** [comment]
@reddyshyam yes you can. The code is the same.

**Comment by reddyshyam** [comment]
> @reddyshyam yes you can. The code is the same.

Ah! Thanks for the update, @vomikan. Let me right away as I always stay on the snapshot stream. 👌🤝

**Pull request merged**
