### PR TITLE
refactor(Versioning): speedup

### PR DESCRIPTION
**Pull request by vomikan**

### CODE REVIEW

**Comment by guanlisheng** [comment]
what's this ?

**Comment by vomikan** [comment]
After this changes function "getProgramVertion()" run one at app start not
9 times.

воскресенье, 29 марта 2015 г. пользователь Lisheng написал:

**Comment by guanlisheng** [comment]
the key is not how many times it will run. i just wanted to check what you want to achieve.

**Comment by guanlisheng** [comment]
@gabriele-v please have a look please.

**Pull request merged**
