### PR TITLE
Show system locale and user application language in About dialog

### PR DESCRIPTION
**Pull request by joshua-stone**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6265)

### CODE REVIEW

**Comment by joshua-stone** [comment]
@whalley This should help address https://github.com/moneymanagerex/moneymanagerex/issues/5213

image

**Comment by joshua-stone** [comment]
It should have broader desktop environment detection now:

image

**Comment by n-stein** [comment]
Windows has an extra bullet point as well:

mmex_JRZKAJLvr1

**Comment by whalley** [comment]
Same on MacOS
CleanShot 2023-10-30 at 20 05 56@2x

**Comment by joshua-stone** [comment]
@n-stein @n-stein This result is consistent with the way [wxPlatformInfo::Get().GetDesktopEnvironment()](https://docs.wxwidgets.org/latest/classwx_app_traits.html#ad333680437446304014c087d2fffedcf) behaves.

Since it doesn't appear that this never worked outside of Linux/X11, it would stand to reason that this should be moved into an #ifdef block like other OS-specific codepaths.

**Pull request merged**
