### PR TITLE
feat(budget.notes): add notes to budget table

### PR DESCRIPTION
**Pull request by guanlisheng**
make sure your code would work on both windows, linux and osx

@moneymanagerex/desktop-mmex-team just to explain how it works to ensure everyone on the same page.

### CODE REVIEW

**Comment by gabriele-v** [comment]
> just to explain how it works to ensure everyone on the same page.

What does it mean?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 99e997b5b246eb23cf3eef216809484108259c39
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
@guanlisheng could we close this PR considering that we have choosen to go with DBUpgrade?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 99e997b5b246eb23cf3eef216809484108259c39
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by omalleypat** [comment]
Can this field still get incorporated into the DBUpgrade procedure - it looks like it was left out in master

**Comment by gabriele-v** [comment]
We have chosen to implement DB Upgrade in 1.3.0 but without any change (only some table creation) to test it.


We will start to officially upgrade DB in 1.4.0 that could be changed to 2.0 because of this major change and maybe remove of _v1 in table names.


Inviato da Android






On Thu, Mar 17, 2016 at 7:13 AM -0700, "omalleypat" <notifications@github.com> wrote:





Can this field still get incorporated into the DBUpgrade procedure - it looks like it was left out in master

---

**Pull request closed without merging**
