### PR TITLE
refactor(Versioning): Simplification

### PR DESCRIPTION
**Pull request by vomikan**

### CODE REVIEW

**Comment by guanlisheng** [comment]
@gabriele-v , please have a look here. thanks!

**Comment by gabriele-v** [comment]
Seems that it isn't correct. 
I'll check it this evening.

**Comment by gabriele-v** [comment]
@vomikan this is wrong:

if (Alpha >= 0)
+        Version.Append(Alpha < 2 ? "-Alpha" : wxString::Format("-Alpha.%i", Alpha));
+    if (Beta >= 0)
+        Version.Append(Beta < 2 ? "-Beta" : wxString::Format("-Beta.%i", Beta));
+    if (RC >= 0)
+        Version.Append(RC < 2 ? "-RC" : wxString::Format("-RC.%i", RC));


In semantic versioning (http://semver.org/)
1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.2

so Alpha or Beta or RC = 0 means Alpha/Beta/RC without suffixes, Alpha/Beta/RC = -1 means stable version, Alpha or Beta or RC = 1 means Alpha.1, Beta.1, RC.1

**Comment by vomikan** [comment]
Why now we will release beta.2 after beta ?
Misundestanding here.


вторник, 17 марта 2015 г. пользователь Gabriele-V написал:

**Comment by gabriele-v** [comment]
If we strictly follow semantic versioning we should release beta.1

But in order to avoid users misunderstanding we could name it beta.2 as well..

**Comment by guanlisheng** [comment]
would we close it ?

**Comment by guanlisheng** [comment]
i will close it now since we don't get agreement here.

**Comment by vomikan** [comment]
It should be accepted!

2015-03-24 3:46 GMT+03:00 Lisheng <notifications@github.com>:

**Comment by guanlisheng** [comment]
I have the same opinion here that your proposal about versioning is incorrect

LiSheng

**Comment by vomikan** [comment]
Did you seen correction?
https://github.com/vomikan/moneymanagerex/commit/12258dc575956c7df246274a8c9f430e1f99242b

2015-03-24 13:49 GMT+03:00 Lisheng <notifications@github.com>:

**Comment by guanlisheng** [comment]
Please send another PR if there is new modification.

LiSheng

**Pull request closed without merging**
