### PR TITLE
Gitignore

### PR DESCRIPTION
**Pull request by dwrj87**
Removed files that are generated by bakefiles from the repo and added them to .gitignore

### CODE REVIEW

**Comment by dwrj87** [comment]
Hmmm, configure isn't being generated on Travis...

**Comment by dwrj87** [comment]
@vomikan Yes, I forgot that need it installed first. Tried adding download, compile and install bakefiles to Travis but that is failing. I shall do some more digging

**Comment by vomikan** [comment]
FYI
http://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-without-an-APT-Repository

2015-05-14 19:57 GMT+03:00 David Jones <notifications@github.com>:

**Comment by dwrj87** [comment]
The error that it's throwing up now has been mentioned before - http://forum.moneymanagerex.org/viewtopic.php?f=7&t=1651

**Comment by dwrj87** [comment]
Closing this pull request for now. I'll do some more research on it

**Pull request closed without merging**
