### PR TITLE
`relocate`→`merge`; `favourite`→`favorite`; Strings ordering `%s`→`%1$s`, `%i`→`%1$i`; Remove `Dialog` and `Window` from source strings

### PR DESCRIPTION
**Pull request by ovari**
Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

https://github.com/moneymanagerex/moneymanagerex/issues/5439#issuecomment-1636655697 point 1

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6113)

Closes https://github.com/moneymanagerex/moneymanagerex/issues/6063
Closes https://github.com/moneymanagerex/moneymanagerex/issues/5881

Thank you

### CODE REVIEW

**Review by tactilis — CHANGES_REQUESTED** [review]
The original string:

"Tag names may not contain the space (' ') character"

is correct.

Please revert this change

**Comment by ovari** [comment]
> Please revert this change

Done.

If you are happy, please merge. Thank you

**Comment by rmelillo76** [comment]
This change needs to be reverted also or is incomplete. 
https://github.com/moneymanagerex/moneymanagerex/blob/6e06766c822d92d6c9c0e9070c6830bb3b395809/src/mmframe.cpp#L736

The latest build failed:
https://ci.appveyor.com/project/whalley/moneymanagerex/build/job/jgi64mm5l6jn59n4

C:\projects\moneymanagerex\src\mmframe.cpp(736): error C2838: 'FAVORITE_PNG': illegal qualified name in member declaration [C:\projects\moneymanagerex\build\src\mmex.vcxproj]
C:\projects\moneymanagerex\src\mmframe.cpp(736): error C2065: 'FAVORITE_PNG': undeclared identifier

**Comment by ovari** [comment]
> This change needs to be reverted also or is incomplete.

Do you know where FAVOURITE_PNG is located so that it can be renamed to FAVORITE_PNG?

Thank you

**Comment by ovari** [comment]
Or are spaces in the names at https://github.com/ovari/moneymanagerex/blob/master/src/mmframe.cpp#L481-L488 not allowed?

@n-stein can you please help with how to fix?

Thank you

**Comment by rmelillo76** [comment]
> Do you know where FAVOURITE_PNG is located so that it can be renamed to FAVORITE_PNG?
> 
> Thank you


https://github.com/moneymanagerex/moneymanagerex/blob/6e06766c822d92d6c9c0e9070c6830bb3b395809/src/images_list.h#L61

https://github.com/moneymanagerex/moneymanagerex/blob/6e06766c822d92d6c9c0e9070c6830bb3b395809/src/images_list.cpp#L207

But I would not recommend you change them.

This is a constant used in the code and not visible to end users. Also changing it could possibly break user themes (please don't hold me to that, would need the devs to opine), these values may map to filenames within the .mmextheme files. (e.g. <theme file>\navigation\FAVOURITE.svg

**Comment by n-stein** [comment]
@ovari I've just had a chance to review this, and I believe there are more changes required:

In general you should be careful when editing non-user facing strings. For example the strings you have edited in Model_Attachment here
https://github.com/moneymanagerex/moneymanagerex/pull/6113/files#diff-e6caf5428e5c73cc9310545431613ad464c273287dfafb0baf8a784ee501f2c0R27-R28
and
https://github.com/moneymanagerex/moneymanagerex/pull/6113/files#diff-e6caf5428e5c73cc9310545431613ad464c273287dfafb0baf8a784ee501f2c0R30-R31
are not user facing but govern how attachments and tags are stored in the database. By changing these strings you have unlinked all account attachments and any tags assigned to split transactions, recurring transactions, or recurring splits in all existing databases. Such changes cannot be made without an accompanied database upgrade to move all existing records to the new RefType strings. These changes should be reverted, and any account attachments or split/recurring tags entered while these changes are in the master branch will be orphaned in the DB (hopefully this is just a few recent transactions in some test databases).

Also changing window names as done here
https://github.com/moneymanagerex/moneymanagerex/pull/6113/files#diff-65966e4d6c9afe262fad35c6461139708417e5fa16cbfe036ac0f54be089c526R47
here
https://github.com/moneymanagerex/moneymanagerex/pull/6113/files#diff-759c01cbdd96adcf94627351448997af1d066159c8e06914eda16ba1fab30beeR46
and here
https://github.com/moneymanagerex/moneymanagerex/pull/6113/files#diff-759c01cbdd96adcf94627351448997af1d066159c8e06914eda16ba1fab30beeR46
should be done carefully as this breaks MMEX's dialog size memory without also adjusting the corresponding mmSetSize code. The system will not be able to recall the last used size of these dialogs. Please note that unlike the dialog "caption" the "name" is an internal attribute and is not user facing. If you want to change the name you also have to make the corresponding adjustment here:
https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1821-L1866

**Comment by ovari** [comment]
Thank you @n-stein for your comment.

It seems that this is too complicated for us.

https://github.com/moneymanagerex/moneymanagerex/pull/6114 has already been closed.

Can https://github.com/moneymanagerex/moneymanagerex/pull/6113 please be reverted?

Can https://github.com/moneymanagerex/moneymanagerex/pull/6115 please be closed?

Thank you for all your wonderful work.

Sorry for wasting so many people's time.

**Comment by rmelillo76** [comment]
> 
> Thank you for all your wonderful work.
> 
> 
> 
> Sorry for wasting so many people's time.

Hi @ovari, no need to apologize! We are all here to help contribute and improve the software for our own use and others in the community. You've clearly spent a lot of time identifying and suggesting changes to help with consistency and improving the user experience. Please don't  let this get you down, we all are working towards a common goal. Thanks @n-stein and @tactilis for reviewing as well.

**Comment by n-stein** [comment]
> You've clearly spent a lot of time identifying and suggesting changes to help with consistency and improving the user experience.

Indeed, I don't see any reason to revert all changes. Just a few minor tweaks needed.

1. Revert changes in Model_Attachment.cpp
2. Update the mmSetSize code I pointed to and change the three "Relocate" to "Merge" as you have done elsewhere.
3. Fix the FAVOURITE_PNG. See my comment on your other PR.

**Comment by n-stein** [comment]
By the way, I believe the reason "BankAccount" and "RecurringTransaction" don't have spaces is because they are used for the filenames of attachments. I just followed suit when I added the TransactionSplit and RecurringTransactionSplit reftypes for tags.

**Comment by ovari** [comment]
Sorry, we are confused with where things are.

> Indeed, I don't see any reason to revert all changes. Just a few minor tweaks needed.

> Revert changes in Model_Attachment.cpp

Should be done at https://github.com/moneymanagerex/moneymanagerex/pull/6115/files#diff-e6caf5428e5c73cc9310545431613ad464c273287dfafb0baf8a784ee501f2c0

> Update the mmSetSize code I pointed to and change the three "Relocate" to "Merge" as you have done elsewhere. The names must match exactly, including case.

Don't know how to change https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1821-L1866

> Fix the FAVOURITE_PNG. See my comment on your other PR.

Should be done at https://github.com/moneymanagerex/moneymanagerex/pull/6115/files#diff-80474aefffdd5e70886979cef3d8e5cf6d4c5129ed74ae6db1e117c11fa6ded4

**Comment by ovari** [comment]
> Update the mmSetSize code I pointed to and change the three "Relocate" to "Merge" as you have done elsewhere. The names must match exactly, including case.

Done. Are these internal names? If so, should they have capital letters? Thank you

**Comment by n-stein** [comment]
> Don't know how to change https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1821-L1866

Just edit lines https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1849
Change the "Relocate Categories" to "Merge categories"

https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1852
"Relocate Payees" to "Merge payees"

https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1864
"Relocate Tags" to "Merge tags"

 > > Fix the FAVOURITE_PNG. See my comment on your other PR.

> Should be done at https://github.com/moneymanagerex/moneymanagerex/pull/6115/files#diff-80474aefffdd5e70886979cef3d8e5cf6d4c5129ed74ae6db1e117c11fa6ded4

See my note in that PR. MENU_FAVOURITES has to be MENU_FAVORITES since that is how the enum is defined in util.h

**Comment by ovari** [comment]
> See my note in that PR. MENU_FAVOURITES has to be MENU_FAVORITES since that is how the enum is defined in util.h

Done at https://github.com/moneymanagerex/moneymanagerex/pull/6115/files#diff-80474aefffdd5e70886979cef3d8e5cf6d4c5129ed74ae6db1e117c11fa6ded4

**Comment by ovari** [comment]
> Just edit lines https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1849
Change the "Relocate Categories" to "Merge categories"
> 
> https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1852
"Relocate Payees" to "Merge payees"
> 
> https://github.com/ovari/moneymanagerex/blob/0eba20b6d330666dc887c514c7f8cc1978443d96/src/util.cpp#L1864
"Relocate Tags" to "Merge tags"

Done at https://github.com/moneymanagerex/moneymanagerex/pull/6115/files#diff-449acf764318b0ca96972daf8d28a28af79ad2c3381044851f2953792fcd8eef

**Comment by n-stein** [comment]
> Are these internal names? If so, should they have capital letters? Thank you

They are internal. The only requirement for case is that the name defined in the dialog constructor matches the name in mmSetSize.

**Comment by rmelillo76** [comment]
@ovari I wanted to mention that I really liked the change from "Relocate" to "Merge". Merge is more commonly used, simple and succinct. 

Any thought on "Relocate Account" - Perhaps we should change it to "Change Account Type"?

**Comment by ovari** [comment]
> Any thought on "Relocate Account" - Perhaps we should change it to "Change Account Type"?

Yes, it seems that the string "Relocate Account" could be improved. Please create an issue as this PR has already been merged.

Would "Edit Account Type" be better?

"Change" implies that it will change.

"Edit" seems to imply that it can be changed, but not definitive. It also seems that "Edit" is the more correct word used in computer terminology.

Just my 2 cents.

**Comment by tactilis** [comment]
@rmelillo76
> Any thought on "Relocate Account" - Perhaps we should change it to "Change Account Type"?

I agree.

@ovari 
> Would "Edit Account Type" be better?
> "Change" implies that it will change.
> "Edit" seems to imply that it can be changed, but not definitive. It also seems that "Edit" is the more correct word used in computer terminology.

I disagree.

We already have Edit Account which allows the user to edit the settings **_of_** an account.

`Change account type...` indicates exactly what the user is can do if they select this.
It's potentially a major step and will be rarely done. It needs to look different to just 'editing'.

The '...' after the menu entry indicate that additional user interaction is needed, so it's obvious that the "Change" will be optional.

**Comment by gabriele-v** [comment]
> By the way, I believe the reason "BankAccount" and "RecurringTransaction" don't have spaces is because they are used for the filenames of attachments. I just followed suit when I added the TransactionSplit and RecurringTransactionSplit reftypes for tags.

Exactly, please double check because I think they are used in database so you cannot change them without a database patch.

**Pull request merged**
