### PR TITLE
Update org.moneymanagerex.MMEX.metainfo.xml.in

### PR DESCRIPTION
**Pull request by ovari**
https://github.com/flathub-infra/website/issues/4229

Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6976)

### CODE REVIEW

**Review by guanlisheng — APPROVED** [review]

**Comment by ovari** [comment]
@joshua-stone can you please merge this into https://github.com/flathub/org.moneymanagerex.MMEX? Thank you

**Comment by joshua-stone** [comment]
@guanlisheng Can you please tag a new release which would have this updated file? I would prefer to not have to maintain a downstream patch.

**Comment by guanlisheng** [comment]
hi @joshua-stone, i am adding the project's release owner @whalley here.

**Comment by ovari** [comment]
Thanks for the new release, it is now fixed for:
* https://flathub.org/de/apps/org.moneymanagerex.MMEX
* https://flathub.org/fr/apps/org.moneymanagerex.MMEX
* https://flathub.org/hu/apps/org.moneymanagerex.MMEX
* https://flathub.org/ru/apps/org.moneymanagerex.MMEX

image

Once https://github.com/flathub-infra/website/issues/4231 is fixed, need to check that the following are displayed correctly:
* https://flathub.org/zh-Hans/apps/org.moneymanagerex.MMEX
* https://flathub.org/zh-Hant/apps/org.moneymanagerex.MMEX

Thank you

**Pull request merged**
