### PR TITLE
fix(#1667): correct table name from db v7

### PR DESCRIPTION
**Pull request by slodki**
fixing bug introduced in PR #1636

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1669)

### CODE REVIEW

**Comment by vomikan** [comment]
@slodki I suggest to use labels for PR:
- fixed for final PR
- Test in case if PR should not be commited
- tbc for preliminary PR

**Comment by slodki** [comment]
I used labels for PR to tag the reason - bug/enchancement.
Label *fixed* for PR is unclear for me - what was fixed? Broken code shouldn't be proposed as PR.

I propose following tags to describe PR status:
- `WIP` (work in progress) - draft proposal ready for comments, or low quality PR not ready for merging jet, PR author is working on it
- `WIP` + `help wanted` - proposal not ready for merge, author is unable to fix/improve - similar to `on hold`?

Review tools can be used to describe required changes required to remove WIP tag if set by different developer then PR author.

**Comment by vomikan** [comment]
For example:
```fix(#1667): correct table name from db v7 #1```
it's a PR that completely fix the bug 1667.
Label 'fix' mean that the bug fixed.

**Comment by slodki** [comment]
This is commit message, PR can consolidate multiple commits with fixes, enchantments, code refactoring...

**Pull request merged**
