### PR TITLE
fix(i18n): use standard wxWidgets translation mechanism

### PR DESCRIPTION
**Pull request by slodki**
* Don't force English locale - use user configured locale settings
* Move/rename locale files to the standard locations
* Don't use one (English) language with multiple catalog files
* Move language selector from Options dialog to View menu
* Store selected language in ini file as integer wxLanguage value
* Auto-select best available translation if previously selected is missing
- Use 2-letter ISO codes in help HTML files
- some tuning in About dialog
- use standard wxWidgets translation catalog (for standard dialogs etc.)
- support standard Unix language env variables (like LANG=it)

locale-menu

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1326)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 9b040cd04c139e397abf2d4c2146e909c1261578
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
This should fix #340 - see [documentation](http://docs.wxwidgets.org/3.0/classwx_translations.html#adb8979906e44477affb150f12c5f145c)

**Comment by slodki** [comment]
Changes in this PR (we don't touching locale settings) should help with solving #1122, #1150, #1153 and similar. We can use system locale settings inside MMEX now.

**Comment by slodki** [comment]
New locale *.mo layout not tested on OSX - please someone check this on Mac

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 21ad7d9b76dba08348714fa88eb10d1ddafe37ba
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
