### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by gerstrong**
General cleanups.

Please do not forget to update the mmex.pot file and write information about the fixed bug in the prerelease [page](https://github.com/moneymanagerex/moneymanagerex/releases).

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/5181)

### CODE REVIEW

**Comment by whalley** [comment]
@gerstrong The mmBitmap -> mmBitMapbundle changes were mostly already made here: https://github.com/moneymanagerex/moneymanagerex/commit/0b395d6d193c973983150c0bcf4b0a158ab1cb62 probably worth fetching the latest code. No clashes so we should be OK

**Comment by gerstrong** [comment]
@whalley I have merged all your changes. Some of hidpi broke with it (especially wxTreeCtrl), but I am okay for now because I am pretty sure we have to look into wxWidgets itself (Still looking to set up an environment for debugging wxwidgets). What you get with this PR are some general C++ cleanups and some proper dimensioning of buttons (nothing major).

**Comment by whalley** [comment]
@gerstrong I note the title of the PR is "Testing", are you happy for it to be merged, or do you need to make further changes?

**Comment by gerstrong** [comment]
Yeah, just saw it, not a good title. Next time will be better :-). Yes, feel free to merge it.

Btw. I also created a PR for the wxWidgets project here: https://github.com/wxWidgets/wxWidgets/pull/22879

**Comment by whalley** [comment]
@gerstrong I missed that you had changed the DB headers, changing usage of std:mem_fun to std:mem_fn, which is fine. However these header files are generated (see:: https://github.com/moneymanagerex/moneymanagerex/blob/master/src/db/readme.txt). I will update the script that generates them (https://github.com/moneymanagerex/moneymanagerex/blob/master/util/sqlite2cpp.py) and re-generate the headers.

**Comment by gerstrong** [comment]
Oh okay. Didn't know that. Thanks for updating the generator. :-)

**Pull request merged**
