### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by dwrj87**
* Sorted out indentation in bakefile
* Fixed some cppcheck warnings regarding C style casts and initialisation lists
* Moved graphics folder to resources
* Renamed some things in Debian build script to make it easier to make out what they are
* Updated source tar download URL in RPM script
* Removed unused file

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9019b761137676dc53e05575c4a0611c6ce85c08
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 132ec9b4d94fd280efe49bec5088474656c5a3f3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c46d2d870f5db4ba3fe57396a8897a4d4a7e4e6d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3e812a02698035a90ae9d4792d8172551ece78db
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ccabfcc1ceb7d6c8289a5aa41f75e2b95bfc14c3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9019b761137676dc53e05575c4a0611c6ce85c08
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 132ec9b4d94fd280efe49bec5088474656c5a3f3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c46d2d870f5db4ba3fe57396a8897a4d4a7e4e6d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3e812a02698035a90ae9d4792d8172551ece78db
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ccabfcc1ceb7d6c8289a5aa41f75e2b95bfc14c3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9019b761137676dc53e05575c4a0611c6ce85c08
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 132ec9b4d94fd280efe49bec5088474656c5a3f3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c46d2d870f5db4ba3fe57396a8897a4d4a7e4e6d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3e812a02698035a90ae9d4792d8172551ece78db
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ccabfcc1ceb7d6c8289a5aa41f75e2b95bfc14c3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 9019b761137676dc53e05575c4a0611c6ce85c08
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: 132ec9b4d94fd280efe49bec5088474656c5a3f3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c46d2d870f5db4ba3fe57396a8897a4d4a7e4e6d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3e812a02698035a90ae9d4792d8172551ece78db
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ccabfcc1ceb7d6c8289a5aa41f75e2b95bfc14c3
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by vomikan** [comment]
Changes is OK
But 
1. Please, return *.icns - it's for MAC
2. Use GitCop format for commits https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

**Comment by vomikan** [comment]
Forget my comment No. 1

**Comment by dwrj87** [comment]
Trying to get used to the GitCop format sorry

**Pull request merged**
