### PR TITLE
fix(GRM): exception constraint failed for the same report name

### PR DESCRIPTION
**Pull request by vomikan**
Also hide reports in main navigation tree if report group name starts with dot.

### CODE REVIEW

**Comment by guanlisheng** [comment]
I don't know why we need this hiding functionality.

**Comment by vomikan** [comment]
1. My goal is to have possibility to run some grm reports from another
report.
2. Some temporary reports better to hide from every day usage.

воскресенье, 19 апреля 2015 г. пользователь Lisheng написал:

**Comment by guanlisheng** [comment]
Would you explain more on the both purpose?

**Comment by vomikan** [comment]
For example, I'll create '.homepage' group with some reports included. All
reports of this group will provide a small peace of info (just table, for
example) . Then these reports will used for build home page.
 20 апр. 2015 г. 1:54 пользователь "Lisheng" <notifications@github.com>
написал:

**Comment by guanlisheng** [comment]
I recommend to use separate table to store the pieces

**Comment by vomikan** [comment]
Your suggestion is yo complex for now.
My suggestion is simple and ma be removed if useless at any time without
any problems.

понедельник, 20 апреля 2015 г. пользователь Lisheng написал:

**Comment by guanlisheng** [comment]
I don't see the complications while your solution make it complex. 

We can't remove your code once there are some pieces report there.

For this standalone table, I would like to create new one instead of dirty reuse 

LiSheng

**Comment by vomikan** [comment]
OK 
Hide group is only for hide not complited reports anly.

**Comment by guanlisheng** [comment]
So let's close this PR .

For GRM, I think we should focus on the UX, for instance, how to build a report easily 

LiSheng

**Pull request closed without merging**
