### PR TITLE
refactor(cmake,appveyor,travis): update build process and CI

### PR DESCRIPTION
**Pull request by slodki**
AppVeyor changes:
* correctly initialize environment for different VisualStudio versions
* add support for different toolchains (120, 140, 141)
  and VS 2013/2015/2017 images
* add support for XP builds (toolchains like 140_xp...)
* add support for Debug builds
* build correct wxWidgets version for different toolchain/target/arch
* move from NMake to MSBuild to support parallel builds and toolchain
  selection
* more detailed package names
  (different toolchain builds share the same name!)
* auto detect and include in packages correct run-time DLLs if available
* include ucrt libraries for XP builds
* add checksums to the artifacts
* patch CMake FindwxWidgets module to support XP builds
- rename script to .appveyor.yml
- do not clone all wxWidgets history only selected version tag
- prefer x64 compiler to produce x86 builds (arch amd64_x86 in place x86)
- do not compress cache twice
- fix path order to fix git clone problems
- do not clone all MMEX versions only 10 last commits
- restore correct version wxWidgets from cache
- fix style of yml file

Travis changes:
* build packages for new distributions
* add priorities for build jobs
* set GitHub check result based on priority jobs only
* do not rename artifacts - use packages names generated by CMake
* add checksums to the artifacts
- do not upload Debug builds
- fix style of yml file

CMake scripts changes:
* do not build in-source - use only /build directory for all tasks
  (/bin removed too)
* add support for multi-configuration generators (remove hard-coded paths
  etc.) like VisualStudio
* move script parts related to specific sources into subdirectory scripts
* do not modify constants.h on-the-fly, use separate versions.h.in
* change version string (in toolchain only!)
  from 1.4.0-ALPHA-1 to 1.4.0~alpha1 to be Linux versionning compatible
* use static MMEXLib to compile sources once and link both mmex and mmex-tests
* use InstallRequiredSystemLibraries CMake module to detect and install
  correct versions of required run-time shared libraries on Windows
* Add settings summary at the end of the configuration phase (all messages
  moved there)
* replace /util/getDistroName.sh with official lsb_release tool incorporated
  into CMake script
* generate correct package names for different distributions with workaround
  for old CMake versions
* auto-detect correct package dependencies for Linux .deb/.rpm packages
* change po/en directory name to locale/en
- move main version numbers into project definition
- store git commit details in versions.h to not clutter command line
- add support for CMake 3.0 to support Debian jessie
- add new section for tuning settings when used from VS IDE
- set many new properties for Linux packages
- change variables prefix to MMEX_
- rename MMEXTest to mmex-tests
- fix style
- small fixes not listed here...

TODO:
- verify if CMake script can be auto loaded and used in the latest
  VisualStudio 2017 IDE
- add support for shared wxWindows (DLL) build for Windows
- replace cached wxWindows binaries with official distributed
  when available (me must compile for XP)
- fix mmex-tests (MMEX_BUILD_TEST=ON) builds (problems with CPPUnit)
- use correct .po/.mo filenames (do not reload message catalog for English
  but change language for the same catalog...)
- fix mmex_tests.rc

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1302)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 484ed74b4013597c6ce3e63eb335394f75ee2f22
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
[AppVeyor](https://ci.appveyor.com/project/slodki/moneymanagerex/build/735) and [Travis](https://travis-ci.org/slodki/moneymanagerex/builds/266247063) build log examples with more combinations to verify build process on different platforms.

**Comment by slodki** [comment]
This PR is related to #1299, #1296, #1293, #1272, #1262, #1261, #1253, #1214, #1126 and #1182 maybe

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 484ed74b4013597c6ce3e63eb335394f75ee2f22
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
I cannot succesfully build on VS2017 with default Ninja generator because of already highlighted problem with PO compiling (command too long, seems that it appends each command instead of executing multiple commands).

Trying to switch to MSBuild (despite slower than Ninja, anyway should be our preferred choiche to keep it aligned with AppVeyor), I've faced to this cmake bug: https://gitlab.kitware.com/cmake/cmake/issues/16811

It's fixed in cmake 3.8.1 but with VS you need to use its embedded version that it's still at 3.8.0

From bug description seems that it works fine if VS2017 it's installed on Win 10 machine (I'm using Win Server 2012R2 which equates to Win Desktop 8.1), I think that @stef145g has this development environment.

Please add this file (rename to CMakeSettings.json) to root folder in order to change VS2017 generator to MSBuild instead of default Ninja
[CMakeSettings.txt](https://github.com/moneymanagerex/moneymanagerex/files/1236360/CMakeSettings.txt)

**Comment by slodki** [comment]
`error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".`

@gabriele-v Did you try to use suggestions from error message above?

You could try to set [CMAKE_SYSTEM_VERSION](https://cmake.org/cmake/help/v3.8/variable/CMAKE_SYSTEM_VERSION.html?highlight=cmake_system_version#system-version-for-host-builds) to different Windows version like 10.xxxx? SDK selection is made basing on this value, so targeting to build Windows 10 binary should select newer SDK version IMHO
>  If it is not Windows 10 then we don't look for a Windows 10 SDK and instead let VS fall back to the 8.1 SDK

**Comment by slodki** [comment]
You could compare test release deployed to GH Releases [here](https://github.com/slodki/moneymanagerex/releases/tag/test-deploy2) and to my private packagecloud repo [here](https://packagecloud.io/slodki/moneymanagerex). Binaries ready to download...

**Comment by gabriele-v** [comment]
Retarget solution it's available only for real VS solution (IE vcxproj or sln), not for cmake projects.

Adding `SET(CMAKE_SYSTEM_VERSION 10.0)` hasn't solved the problem, I don't now which value does it exactly have on Windows 10. Tried to set 10.0.15063.0 (same of installed Windows SDK) but still no success.


In test release seems that win32_xp it's missing

**Comment by slodki** [comment]
I can see `CMAKE_SYSTEM_VERSION` value at [AppVeyor log](https://ci.appveyor.com/project/slodki/moneymanagerex/build/741/job/j9m29yafu8fcmcha#L112) set to `10.0.14393` (and SDK version `10.0.14393.0` used BTW). Try this value.

On VS2013 and VS2015 `CMAKE_SYSTEM_VERSION` was set to `6.3.9600`.
More numbers at [Wikipedia](https://en.wikipedia.org/wiki/Ver_(command)#Version_list).

**Comment by slodki** [comment]
I can see both win32_xp (portable and installer) at Releases page.

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 484ed74b4013597c6ce3e63eb335394f75ee2f22
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
@gabriele-v I fixed your json and added to this PR.

Maybe we should use
```json
"buildRoot": "${workspaceRoot}\\build\\${name}"
```
or
```json
"buildRoot": "${projectDir}\\build\\${name}"
```
>${workspaceRoot} – provides the full path to the workspace folder
>${projectDir} – the full path to the folder of the root CMakeLists.txt file

**Comment by gabriele-v** [comment]
You are right, win32_xp is there.

Yes, I prefer that too, but you have noticed that build must stay outside of source folder so I left as default.

Still no luck instead with `CMAKE_SYSTEM_VERSION`

**Comment by slodki** [comment]
Look at CMake [FAQ](https://cmake.org/Wiki/CMake_FAQ#Out-of-source_build_trees) - *out of source* build can be placed in **separate** directory somewhere in the source tree. The main goal is to separate generated files from the sources.

The `${projectDir}\\build\\${name}` is classic *out of source* example.

**Comment by gabriele-v** [comment]
Ok, agree to change it as proposed

**Comment by slodki** [comment]
I had installed VS2017 moment ago.

Trying to run clean cmake project (without json file).
IDE is running cmake with some predefined (?) parameters:

`C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\test\CMakeBuilds\0f3a161c-0af0-7335-9601-9cad962f8fc3\build\x86-Debug\install"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\test\source\repos\moneymanagerex"`
```
1> Working directory: C:\Users\test\CMakeBuilds\0f3a161c-0af0-7335-9601-9cad962f8fc3\build\x86-Debug
1> -- The C compiler identification is MSVC 19.11.25506.0
1> -- The CXX compiler identification is MSVC 19.11.25506.0
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe -- works
1> -- Detecting CXX compiler ABI info
1> -- Detecting CXX compiler ABI info - done
1> -- Detecting CXX compile features
1> -- Detecting CXX compile features - done
1> -- Found wxWidgets: C:/wxWidgets-3.1.0/lib/vc_lib/wxmsw31ud_core.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxmsw31ud_qa.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxbase31ud_net.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxmsw31ud_html.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxbase31ud_xml.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxmsw31ud_aui.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxmsw31ud_adv.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxmsw31ud_stc.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxmsw31ud_webview.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxbase31ud.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxscintillad.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxpngd.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxtiffd.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxjpegd.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxzlibd.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxregexud.lib;C:/wxWidgets-3.1.0/lib/vc_lib/wxexpatd.lib;winmm;comctl32;oleacc;rpcrt4;shlwapi;version;wsock32 (found version "3.1.0") 
1> -- Found Gettext: C:/Program Files/gettext-iconv/bin/msgmerge.exe  
1> -- 
1> -- MMEX configuration summary
1> -- ==========================
1> -- Version        : 1.4.0~alpha3
1> -- Build tests    : OFF
1> -- Host system    : Windows AMD64
1> -- Target system  : Windows x86
1> -- Build types    : Debug
1> -- Generator      : Ninja
1> -- Build command  : ninja.exe
1> -- VC installed   : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\
1> -- Install prefix : C:/Users/test/CMakeBuilds/0f3a161c-0af0-7335-9601-9cad962f8fc3/build/x86-Debug/install
1> -- 
1> -- Versions
1> -- ========
1> -- Windows : 6.3.9600
1> -- CMake : 3.8.0-MSVC_2
1> -- MSVC : 19.11.25506.0
1> -- wxWidgets : 3.1.0
1> -- 
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: C:/Users/test/CMakeBuilds/0f3a161c-0af0-7335-9601-9cad962f8fc3/build/x86-Debug
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Collating data ...
1> Target info extraction done.
```

And `MSVC_IDE` is not defined with Ninja generator - it can be used [with VS generator only](https://github.com/Kitware/CMake/blob/989ca432e4d842e50f07a1ff05dc4a65fc9881cb/Tests/CheckCompilerRelatedVariables/CMakeLists.txt#L74)

I skipped to modify install prefix if set by user - but IDE modifies it at command line...

I must do some more testing.

PS. We don't need msbuild.exe and can use Ninja as long as we don't want to use specific toolchain (like XP version). Ninja should be enough to run normal debug session in IDE with default toolchain installed.

**Pull request merged**
