### PR TITLE
fix(#3427) - Min OSX build 10.10

### PR DESCRIPTION
**Pull request by whalley**
make sure your code would work on both windows, linux and osx

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/3458)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 41a955b7a935602a95f80abb0a7667528a8271e7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 41a955b7a935602a95f80abb0a7667528a8271e7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 5685f23d5492e6d1340b0f058072f93cf1d6e860
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by whalley** [comment]
@vomikan MacOS build is timing out, is there anyway to increase available build time or is this fixed with Travis config?

**Comment by vomikan** [comment]
> @vomikan MacOS build is timing out, is there anyway to increase available build time or is this fixed with Travis config?

I don't know.

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 41a955b7a935602a95f80abb0a7667528a8271e7
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 5685f23d5492e6d1340b0f058072f93cf1d6e860
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 3243730cdf9bf6870e50fe303157705c11a8cb7a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
