### PR TITLE
clean(currencyformats): remove unused UNIT_NAME and CENT_NAME

### PR DESCRIPTION
**Pull request by slodki**
See also moneymanagerex/database#21 and #1158 #1528
Upgrade procedure tested.

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1552)

### CODE REVIEW

**Comment by stef145g** [comment]
Please refer to my comments in https://github.com/moneymanagerex/database/pull/21

**Comment by slodki** [comment]
Merged with database crypto upd - now uses database v9

**Comment by slodki** [comment]
We should merge moneymanagerex/database#21 too.
@MisterY we bumped database to v9 on desktop side

**Comment by MisterY** [comment]
Thanks for letting me know, @slodki! 
BTW, I've migrated my home PC to Linux and have yet to set up a development environment again.

**Pull request merged**
