### PR TITLE
feat(#1207): initial commit

### PR DESCRIPTION
**Pull request by vomikan**
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1492)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 19e5050f32f25e2d9e54842827cc173ae974d0b6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 19e5050f32f25e2d9e54842827cc173ae974d0b6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 624b177b8a3f38dd23f4df494e938de152b0386e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 19e5050f32f25e2d9e54842827cc173ae974d0b6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 624b177b8a3f38dd23f4df494e938de152b0386e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 21d06f9bedb6e8288036e80f1138e30072c81543
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 19e5050f32f25e2d9e54842827cc173ae974d0b6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 624b177b8a3f38dd23f4df494e938de152b0386e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 21d06f9bedb6e8288036e80f1138e30072c81543
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by slodki** [comment]
Did you checked https://github.com/stef145g/moneymanagerex/tree/rapidjson ?

**Pull request closed without merging**
