### PR TITLE
fix(#1257): refresh copyright info

### PR DESCRIPTION
**Pull request by vomikan**
make sure your code would work on both windows, linux and osx

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1680)

### CODE REVIEW

**Comment by slodki** [comment]
See PR #1685 for tool generating author list from git repo:

Years | Author | Commits
--- | --- | ---
2006 | Madhan Kanagavel | 1
2013 2014 2015 2016 2017 2018 | Nikolay Akimov | 2410
2013 2014 2015 2016 2017 2018 | Stefano Georgio | 516
2013 2014 2015 2016 2017 | James Higley | 464
2013 2014 2015 2016 2017 | Lisheng Guan | 1494
2013 | moneymanagerex | 1
2014 2015 2016 2017 2018 | Gabriele Villa | 368
2014 2015 2016 2017 | Patrick O'Malley | 37
2014 2015 2016 | giuseppepaoletti | 43
2014 | Mark Clayton | 4
2014 | paulle | 1
2014 | s2108312 | 4
2014 | thehobbit | 15
2014 | yfzhang | 8
2015 2016 | David Jones | 48
2015 2016 | kolmo7 | 4
2015 2016 | Yosef Shatsky | 18
2015 2017 | Kamil Wcislo | 3
2015 | David Jones | 64
2015 | Giuseppe Bertone | 1
2015 | Hüseyin Uslu | 1
2015 | jeffjl74 | 2
2015 | kolmo7 | 1
2015 | Liudas Alisauskas | 2
2015 | loki36 | 18
2015 | Patrick Eigensatz | 1
2016 | Arnaud Quirin | 1
2016 | Dawid Gaweł | 1
2016 | Julien Cornebise | 2
2016 | Patrick O'Malley | 1
2016 | Vincent Bermel | 1
2017 2018 | Tomasz Słodkowicz | 193
2017 | BentleyJOakes | 2
2017 | gjroelofs | 1
2017 | sillawned | 1
2017 | Stephen Groat | 5
2017 | Tomáš Frťala | 22
2018 | Alexey Loukianov | 1

**Comment by guanlisheng** [comment]
Great stats.

**Comment by slodki** [comment]
The same as `git shortlog -se --all` but with years added

**Comment by vomikan** [comment]
Perhaps, the years are incorrect. 
Before github hosting we was developing on SF svn.

**Comment by slodki** [comment]
SVN repo was migrated to Git without history (as a tar ball maybe?)
Is somewhere SVN repo copy available?

**Pull request merged**
