### PR TITLE
new(#6860): include scheduled transactions in transactions panels

### PR DESCRIPTION
**Pull request by georgeef**
This PR replaces #6861, #6873, #6878, #6880. It is based on 331803150.

See #6860 and the description in the PRs above.

- - -
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/6981)

### CODE REVIEW

**Comment by whalley** [comment]
@georgeef Thanks for the re-submit. Have merged.

**Comment by whalley** [comment]
@georgeef Balance calculation is wrong following this change...

CleanShot 2024-12-02 at 08 41 53

**Comment by georgeef** [comment]
@whalley 
Thanks for the bug report. I have sent a quick fix. I'll check again the balance/flow calculations more thoroughly in next days.

**Comment by whalley** [comment]
> @whalley Thanks for the bug report. I have sent a quick fix. I'll check again the balance/flow calculations more thoroughly in next days.

Thanks, looks good now.

**Comment by georgeef** [comment]
@whalley 
I tested the balance calculations for many cases in the past, apparently this bug slipped in a late refactoring.

**Pull request merged**
