### PR TITLE
Linux packaging

### PR DESCRIPTION
**Pull request by dwrj87**
The RPM and DEB packaging scripts now share more in common, so only need to change the version number, release date, etc in 1 place

Still a lot more to be done on both of the scripts, and I haven't even looked at the puppy one yet. I will get around to them as time allows

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 166856251f12bf0358a3af7a7994d82e9af35bef
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 79497a134bfb1a73b713f296eb543073b3de20fb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: bb2eac3a238cea93cc6038141b2b43ee51329fc4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 224a4d3ec0472037a9a8025b7f7b4ea0178fd4eb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 166856251f12bf0358a3af7a7994d82e9af35bef
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 79497a134bfb1a73b713f296eb543073b3de20fb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Your subject line is longer than 72 characters

 * Commit: bb2eac3a238cea93cc6038141b2b43ee51329fc4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 224a4d3ec0472037a9a8025b7f7b4ea0178fd4eb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by vomikan** [comment]
Please do not spend time for Puppy. They can use deb packages.
Could you look on
https://github.com/moneymanagerex/moneymanagerex/blob/master/util/svn_to_launchpad.sh
?

Nikolay
10 марта 2015 г. 6:58 пользователь "David Jones" <notifications@github.com>
написал:

**Comment by dwrj87** [comment]
I shall try my best

**Pull request merged**
