### PR TITLE
refactor(Images.List): no constants but enum

### PR DESCRIPTION
**Pull request by vomikan**

### CODE REVIEW

**Comment by dwrj87** [comment]
@vomikan @guanlisheng 

This commit builds OK but makes it crash on startup for me

**Comment by vomikan** [comment]
What is OS?

2015-04-30 2:28 GMT+03:00 David Jones <notifications@github.com>:

**Comment by vomikan** [comment]
Should work now

https://github.com/moneymanagerex/moneymanagerex/commit/f8135d114bd5da31895c6ed9f5e1e57b5bee5ba5

2015-04-30 10:01 GMT+03:00 Nikolay Akimov <nikolay.akimov@gmail.com>:

**Comment by dwrj87** [comment]
Yes, this fixes it

**Pull request merged**
