### PR TITLE
refactor(BuildSystem): CMake Conversion (#679)

### PR DESCRIPTION
**Pull request by dwrj87**
I'm afraid I cannot test this with Windows or OSX, as I'm not familiar enough with Windows/VS and don't have a Mac, so you can either let me know if you find any bugs and I'll try and fix them or you can fix them yourselves.

The only 2 problems I have on Linux are that the CPPUnit library is missing a file (include/cppunit/config-auto.h), and with the Lithuanian PO file, it's parsing "10%" as a C string. Other than that, I've been using it for weeks and it works every time.

Some possible improvements for the future

- CMake comes with an installer generator for a few operating systems

### CODE REVIEW

**Comment by vomikan** [comment]
Just delete #, c-format in lithuanian.po file to fix the issue with the Lithuanian PO file

~~~~~
#, c-format
msgid ""
"Tip to get out of debt: Pay yourself 10% first. Put this into an account "
"that is hard to touch. Make sure it is a chore to get the money out (you "
"have to drive to the bank), so you will only tap it consciously and for "
"major expenses."
msgstr ""
"Patarimas kaip išsikapstyti iš skolų: Mokėkite pirmiausiai 10% sau. Padėkite "
"tai į sąskaitą, kurią sunku pasiekti. Įsitikinkite, kad yra labai nepatogu "
"pasiimti pinigus iš ten (reikia važiuoti iki banko), tam kad panaudoti jos "
"pinigus tik sąmoningai ir svarbiems pirkiniams."
~~~~~

**Comment by dwrj87** [comment]
I did do that locally, but the problem with that is that whenever the PO file is updated, the error will pop up again. Just pushed a commit that should fix it permanently

**Comment by vomikan** [comment]
I can't buils mmex locally with VS2013 and cmake-3.1.2-win32-x86.zip
~~~~~
Ошибка	1	error LNK2019: ссылка на неразрешенный внешний символ _Scintilla_LinkLexers в функции "public: bool __thiscall wxStyledTextCtrl::Create(class wxWindow *,int,class wxPoint const &,class wxSize const &,long,class wxString const &)" (?Create@wxStyledTextCtrl@@QAE_NPAVwxWindow@@HABVwxPoint@@ABVwxSize@@JABVwxString@@@Z)	C:\Dev\cmake\wxmsw30u_stc.lib(stc.obj)	mmex
~~~~~~

**Comment by dwrj87** [comment]
@vomikan Last commit should fix that problem. I have no idea what is causing the current build problem on Travis however. Could you take a look at it for me please?

**Comment by vomikan** [comment]
I wont to help but seems it quite difficult for now.
I've build mmex.exe x32 but can't run it. 
Output is:
~~~~~
C:\Dev\cmake\bin\Release>mmex.exe -v
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
~~~~~

**Comment by vomikan** [comment]
Sorry, I want to help but seems it quite difficult for me now.

**Comment by dwrj87** [comment]
No problem. I shall keep working at it, and I shall have another go at using Windows/VS

**Pull request closed without merging**
