### PR TITLE
currency fixes

### LINKED ISSUE #1449: add missing currencies using ISO 2417:2015 list
helllo,

i wish it was possible to include zambian Kwacha as a currency with the right acronym (ZMW), and that already input values for which the currency exchange was already calculated, would not change once the exchange rate is updated/recalculated. greetings

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [x] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [x] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

### PR DESCRIPTION
**Pull request by slodki**
This PR requires moneymanagerex/database#22 and will fix #1449, #1527, #1528, #1582 and moneymanagerex/database#20.
@MisterY database will be upgraded to v10

I'll add checkbox next to "Show All" labeled "Show Historic" to toggle hide/display currencies no longer official (like DEM, FRF, PLZ etc.).

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1592)

### CODE REVIEW

**Comment by vomikan** [comment]
:lgtm: ok

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/1592#-:-LAt-wch76NNTdxzwDoR:bks4n0r)*

**Comment by stef145g** [comment]
I was not able to upgrade this test database
[3211 - Copy.zip](https://github.com/moneymanagerex/moneymanagerex/files/1945333/3211.-.Copy.zip)

**Comment by slodki** [comment]
@stef145g I've lost one change while merging PR...

**Comment by slodki** [comment]
What about removing funds codes from list? They are included in ISO standard, used in similar way as currency, users can have accounts denominated in them:

> 3   Terms and definitions
> [...]
> 3.3 fund
> artificial currency used as calculation basis for another currency (or currencies) and/or for accounting purposes

But are rather exotic like:

Name | Symbol | Description
--- | --- | ---
Mvdol | BOV | For indexation purposes and denomination of certain financial instruments (e.g. treasury bills). The Mvdol is set daily by the Central Bank of Bolivia based on the official USD/BOB rate.
WIR Franc | CHW | WIR Bank for use with the EFTPOS system with their own WIR-card and the Electronic Banking Services.
WIR Euro | CHE | WIR Bank for use with the EFTPOS system with their own WIR-card and the Electronic Banking Services
Unidad de Fomento | CLF | The CLF is a daily economically-financial unit calculated by the Central Bank of Chile according to inflation (as measured by the Chilean Consumer Price Index of the previous month). The value of the CLF is expressed in terms of Chilean Pesos per CLF. The use of CLF has been widely extended to all types of bank loans, financial investments (time deposits, mortgages and other public or private indexed instruments), contracts and fees in some cases.
Unidad de Valor Real (UVR) | COU | The UVR is a daily account unit set by the Central Bank of Colombia according to the variation in the Consumer Price Index of Colombia. The value of UVR is expressed in terms of Colombian Pesos per UVR. It is used to denominate and update mortgage loans and some public debt bonds.
Mexican Unidad de Inversion (UDI) | MXV | The UDI is an inflation adjusted mechanism set by the Central Bank of Mexico according to the variation in the Mexican Consumer Price Index. The value of the UDI is expressed in terms of Mexican Pesos per UDI. It is used to denominate mortgage loans, some bank deposits with maturities of 3 month or more and Government bonds (UDIBONOS).
US Dollar Next day | USN | ”Next day“ funds are immediately available for transfer in like funds, and, subject to settlement, available the next business day for same day funds transfer or withdrawal in cash.
Uruguay Peso en Unidades Indexadas (UI) | UYI | The UYI (UI) is used for issuance of debt instruments by the Uruguayan government in the international global bond market.  It is calculated based on an established methodology using underlying inflationary statistics in the Uruguayan market. (Introduced in 2002).

The lis of historic founds is longer...

**Comment by stef145g** [comment]
file: **util/build_db_tables.bat** requires correction in lines 20 and 22 due to name change of generated files.

**Comment by slodki** [comment]
@stef145g Tu run `sqliteupgrade2cpp.py` you must have only upgrade files with SQL in directory given as parameter. Additional files in /database dir generate this error. I simply copy files to temp dir to use `sqliteupgrade2cpp.py`. You can always add filtering rule to ignore additional files...

I changed filenames because *upgrade* take place inside MMEX and script can only *update* data in already upgraded database.

**Comment by slodki** [comment]
@stef145g upgrade script fixed and working

**Comment by slodki** [comment]
Fixed `sqliteupgrade2cpp.py` correctly selects only `database_version_*.sql` files now.

**Comment by stef145g** [comment]
I can now upgrade the previous file but running in debug mode getting:
screenshot 2018-04-26 11 12 51

I also got this error:
screenshot 2018-04-26 11 10 46

======================
Because of the above issues, I created a new database at mmex version 0.9.7.0 and tried to update it. This failed at version 9 with this result:
[mmex_0970.mmb - Copy.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/1949341/mmex_0970.mmb.-.Copy.mmb.zip)
screenshot 2018-04-26 11 34 21

**Comment by stef145g** [comment]
I tried to update a copy of my working database and I get this error:
screenshot 2018-04-26 11 54 14

**Comment by stef145g** [comment]
After deleting the index in my working copy database, I was able to successfully update it, but also got the debug warning only.
screenshot 2018-04-26 11 59 37

**Comment by slodki** [comment]
`VIEW_ACCOUNTS_ALL_STR` assert is caused by following change:
https://github.com/moneymanagerex/moneymanagerex/pull/1592/commits/caa339779cdd5780e0da7329620ce38c613ea606#diff-d1d8a04c2bc0c4a10f55cd0fee9ac17fL252

I changed wrong string capitalization but this value is stored as user setting too.
This assert is not displayed in release build and user can select new value in MMEX option settings (after upgrage it will be empty if ALL was selected previously).

**Comment by slodki** [comment]
`TEMPLATECONTENT` problem seems not related to above changes for me.

**Comment by slodki** [comment]
@stef145g Could you describe more details for scenario with index problem? I cannot reproduce it on my PC...

**Comment by slodki** [comment]
`UNIQUE constraint failed` is #1578.
This is problem with data stored in your database not detected by previous MMEX versions. CURRENCY_SYMBOL should be not null and unique but it was not checked. New version verify this during upgrade procedure.
I don't have any idea for universal fix for this.

**Comment by slodki** [comment]
Please use  #1578 to discuss wrong entries (that do not meet the constraints).

This database version change is very easy and simple - we remove unused columns or add new without breaking relations or integrity. The more complicated change wasn't well prepared in MMEX v1.1.0...

**Pull request merged**
