### PR TITLE
Feature/master/ofx2qif

### PR DESCRIPTION
**Pull request by loki36**
add convert ofx to qif under linux using ofx2qif command depending of ofx package
#300

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f5204293c27c0f1cfa1c0266d14b0a8c78b1114a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ef77122f5acd3abbb775880d28eb404ba17191be
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a87012bbdf7313167f0d7af9d0a1374b4052d622
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 207c97b43ec940d8c2e033e1d028137c64c74ad0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e17694248cd9e48ca286ec3a7c1d1018a8586083
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: abd05163251f622044e1de943a9e79ed13ed4951
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c1330724dad0a62b17e1872206de78e12ecb0334
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f5204293c27c0f1cfa1c0266d14b0a8c78b1114a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ef77122f5acd3abbb775880d28eb404ba17191be
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a87012bbdf7313167f0d7af9d0a1374b4052d622
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 207c97b43ec940d8c2e033e1d028137c64c74ad0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e17694248cd9e48ca286ec3a7c1d1018a8586083
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: abd05163251f622044e1de943a9e79ed13ed4951
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c1330724dad0a62b17e1872206de78e12ecb0334
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
If it works fine, what about insert ofxtoqif as MMEX 3rd library?

**Comment by loki36** [comment]
I think it's the best and easy way but for this we need to find the compile version for windows and for mac

**Comment by vomikan** [comment]
Please make a patch for this changes and apply it for new branch.
Remove white spaces and tabs.
Then provide another PR.
Thanks.

**Comment by loki36** [comment]
ok
I will do it asap

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f5204293c27c0f1cfa1c0266d14b0a8c78b1114a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ef77122f5acd3abbb775880d28eb404ba17191be
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a87012bbdf7313167f0d7af9d0a1374b4052d622
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 207c97b43ec940d8c2e033e1d028137c64c74ad0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e17694248cd9e48ca286ec3a7c1d1018a8586083
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: abd05163251f622044e1de943a9e79ed13ed4951
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c1330724dad0a62b17e1872206de78e12ecb0334
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f5204293c27c0f1cfa1c0266d14b0a8c78b1114a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: ef77122f5acd3abbb775880d28eb404ba17191be
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: a87012bbdf7313167f0d7af9d0a1374b4052d622
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 207c97b43ec940d8c2e033e1d028137c64c74ad0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e17694248cd9e48ca286ec3a7c1d1018a8586083
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: abd05163251f622044e1de943a9e79ed13ed4951
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c1330724dad0a62b17e1872206de78e12ecb0334
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by vomikan** [comment]
It's bad style to use OS specific code. On other hand there are no open ofx2qif converters writen on c++.

**Comment by guanlisheng** [comment]
i have the similar concern as Nikolay and would we implement a general and cross platform one?

LiSheng 

在 2015年4月16日，下午10:21，Nikolay <notifications@github.com> 写道：

It's bad style to use OS specific code. On other hand there are no open ofx2qif converters writen on c++.

**Comment by dwrj87** [comment]
According to libofx homepage, it is written in C++

http://libofx.sourceforge.net/

**Comment by vomikan** [comment]
The same https://github.com/arolson101/libofx ?

2015-04-18 23:28 GMT+03:00 David Jones <notifications@github.com>:

**Comment by dwrj87** [comment]
I *think* so

**Comment by vomikan** [comment]
Lets close this PR.
Try to add  https://github.com/arolson101/libofx as submodule and use it for all systems.

**Pull request closed without merging**
