### PR TITLE
Fixes(#2435): Crash on wrong db version

### PR DESCRIPTION
**Pull request by gabriele-v**
WAIT, DO NOT MERGE!!

---
This change is [Reviewable](https://reviewable.io/reviews/moneymanagerex/moneymanagerex/2439)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for your pull request while there were the following issues

 * Commit: 1848b2a3733ef6d43793ff52ecffa5d21f4ca202
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, cleanup, format, doc, clean**

Guidelines are available at https://github.com/moneymanagerex/moneymanagerex/wiki/GitCop

---
This message was auto-generated by https://gitcop.com

**Comment by gabriele-v** [comment]
@vomikan I've got now how it's working, I'll provide a new patch

**Comment by vomikan** [comment]
Could you please use Slack for quick conversations?

**Comment by gabriele-v** [comment]
Ok I'll have a look

**Pull request closed without merging**
